// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"fmt"
)

type BaseResponse struct {
	StatusCode int64  `thrift:"status_code,1" frugal:"1,default,i64" json:"status_code"`
	StatusMsg  string `thrift:"status_msg,2" frugal:"2,default,string" json:"status_msg"`
}

func NewBaseResponse() *BaseResponse {
	return &BaseResponse{}
}

func (p *BaseResponse) InitDefault() {
}

func (p *BaseResponse) GetStatusCode() (v int64) {
	return p.StatusCode
}

func (p *BaseResponse) GetStatusMsg() (v string) {
	return p.StatusMsg
}
func (p *BaseResponse) SetStatusCode(val int64) {
	p.StatusCode = val
}
func (p *BaseResponse) SetStatusMsg(val string) {
	p.StatusMsg = val
}

func (p *BaseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponse(%+v)", *p)
}

var fieldIDToName_BaseResponse = map[int16]string{
	1: "status_code",
	2: "status_msg",
}

type NilResponse struct {
}

func NewNilResponse() *NilResponse {
	return &NilResponse{}
}

func (p *NilResponse) InitDefault() {
}

func (p *NilResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NilResponse(%+v)", *p)
}

var fieldIDToName_NilResponse = map[int16]string{}

type PageRequest struct {
	Page     int32 `thrift:"page,1" frugal:"1,default,i32" json:"page"`
	PageSize int32 `thrift:"page_size,2" frugal:"2,default,i32" json:"page_size"`
}

func NewPageRequest() *PageRequest {
	return &PageRequest{
		Page:     1,
		PageSize: 10,
	}
}

func (p *PageRequest) InitDefault() {
	p.Page = 1
	p.PageSize = 10
}

func (p *PageRequest) GetPage() (v int32) {
	return p.Page
}

func (p *PageRequest) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *PageRequest) SetPage(val int32) {
	p.Page = val
}
func (p *PageRequest) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *PageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageRequest(%+v)", *p)
}

var fieldIDToName_PageRequest = map[int16]string{
	1: "page",
	2: "page_size",
}

type PageResponse struct {
	Total    int64 `thrift:"total,1" frugal:"1,default,i64" json:"total"`
	Page     int32 `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize int32 `thrift:"page_size,3" frugal:"3,default,i32" json:"page_size"`
}

func NewPageResponse() *PageResponse {
	return &PageResponse{}
}

func (p *PageResponse) InitDefault() {
}

func (p *PageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *PageResponse) GetPage() (v int32) {
	return p.Page
}

func (p *PageResponse) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *PageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *PageResponse) SetPage(val int32) {
	p.Page = val
}
func (p *PageResponse) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *PageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageResponse(%+v)", *p)
}

var fieldIDToName_PageResponse = map[int16]string{
	1: "total",
	2: "page",
	3: "page_size",
}
