// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type QuestionDifficulty int64

const (
	QuestionDifficulty_QD_NOT_SPECIFIED QuestionDifficulty = 0
	QuestionDifficulty_MEDIUM           QuestionDifficulty = 2
	QuestionDifficulty_HARD             QuestionDifficulty = 3
)

func (p QuestionDifficulty) String() string {
	switch p {
	case QuestionDifficulty_QD_NOT_SPECIFIED:
		return "QD_NOT_SPECIFIED"
	case QuestionDifficulty_MEDIUM:
		return "MEDIUM"
	case QuestionDifficulty_HARD:
		return "HARD"
	}
	return "<UNSET>"
}

func QuestionDifficultyFromString(s string) (QuestionDifficulty, error) {
	switch s {
	case "QD_NOT_SPECIFIED":
		return QuestionDifficulty_QD_NOT_SPECIFIED, nil
	case "MEDIUM":
		return QuestionDifficulty_MEDIUM, nil
	case "HARD":
		return QuestionDifficulty_HARD, nil
	}
	return QuestionDifficulty(0), fmt.Errorf("not a valid QuestionDifficulty string")
}

func QuestionDifficultyPtr(v QuestionDifficulty) *QuestionDifficulty { return &v }
func (p *QuestionDifficulty) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = QuestionDifficulty(result.Int64)
	return
}

func (p *QuestionDifficulty) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type QuestionEntity struct {
	Id       int64     `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Question *Question `thrift:"question,2" frugal:"2,default,Question" json:"question"`
}

func NewQuestionEntity() *QuestionEntity {
	return &QuestionEntity{}
}

func (p *QuestionEntity) InitDefault() {
}

func (p *QuestionEntity) GetId() (v int64) {
	return p.Id
}

var QuestionEntity_Question_DEFAULT *Question

func (p *QuestionEntity) GetQuestion() (v *Question) {
	if !p.IsSetQuestion() {
		return QuestionEntity_Question_DEFAULT
	}
	return p.Question
}
func (p *QuestionEntity) SetId(val int64) {
	p.Id = val
}
func (p *QuestionEntity) SetQuestion(val *Question) {
	p.Question = val
}

func (p *QuestionEntity) IsSetQuestion() bool {
	return p.Question != nil
}

func (p *QuestionEntity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuestionEntity(%+v)", *p)
}

var fieldIDToName_QuestionEntity = map[int16]string{
	1: "id",
	2: "question",
}

type Question struct {
	Category   string   `thrift:"category,1" frugal:"1,default,string" json:"category"`
	Difficulty int32    `thrift:"difficulty,2" frugal:"2,default,i32" json:"difficulty"`
	Title      string   `thrift:"title,3" frugal:"3,default,string" json:"title"`
	Content    string   `thrift:"content,4" frugal:"4,default,string" json:"content"`
	Answer     string   `thrift:"answer,5" frugal:"5,default,string" json:"answer"`
	Tags       []string `thrift:"tags,6" frugal:"6,default,list<string>" json:"tags"`
	CreatedAt  int64    `thrift:"created_at,7" frugal:"7,default,i64" json:"created_at"`
}

func NewQuestion() *Question {
	return &Question{}
}

func (p *Question) InitDefault() {
}

func (p *Question) GetCategory() (v string) {
	return p.Category
}

func (p *Question) GetDifficulty() (v int32) {
	return p.Difficulty
}

func (p *Question) GetTitle() (v string) {
	return p.Title
}

func (p *Question) GetContent() (v string) {
	return p.Content
}

func (p *Question) GetAnswer() (v string) {
	return p.Answer
}

func (p *Question) GetTags() (v []string) {
	return p.Tags
}

func (p *Question) GetCreatedAt() (v int64) {
	return p.CreatedAt
}
func (p *Question) SetCategory(val string) {
	p.Category = val
}
func (p *Question) SetDifficulty(val int32) {
	p.Difficulty = val
}
func (p *Question) SetTitle(val string) {
	p.Title = val
}
func (p *Question) SetContent(val string) {
	p.Content = val
}
func (p *Question) SetAnswer(val string) {
	p.Answer = val
}
func (p *Question) SetTags(val []string) {
	p.Tags = val
}
func (p *Question) SetCreatedAt(val int64) {
	p.CreatedAt = val
}

func (p *Question) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Question(%+v)", *p)
}

var fieldIDToName_Question = map[int16]string{
	1: "category",
	2: "difficulty",
	3: "title",
	4: "content",
	5: "answer",
	6: "tags",
	7: "created_at",
}

type CategoryInfo struct {
	Name  string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Count int32  `thrift:"count,2" frugal:"2,default,i32" json:"count"`
}

func NewCategoryInfo() *CategoryInfo {
	return &CategoryInfo{}
}

func (p *CategoryInfo) InitDefault() {
}

func (p *CategoryInfo) GetName() (v string) {
	return p.Name
}

func (p *CategoryInfo) GetCount() (v int32) {
	return p.Count
}
func (p *CategoryInfo) SetName(val string) {
	p.Name = val
}
func (p *CategoryInfo) SetCount(val int32) {
	p.Count = val
}

func (p *CategoryInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CategoryInfo(%+v)", *p)
}

var fieldIDToName_CategoryInfo = map[int16]string{
	1: "name",
	2: "count",
}
