// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type UserStatus int64

const (
	UserStatus_US_NOT_SPECIFIED UserStatus = 0
	UserStatus_ACTIVE           UserStatus = 1
	UserStatus_INACTIVE         UserStatus = 2
	UserStatus_BANNED           UserStatus = 3
)

func (p UserStatus) String() string {
	switch p {
	case UserStatus_US_NOT_SPECIFIED:
		return "US_NOT_SPECIFIED"
	case UserStatus_ACTIVE:
		return "ACTIVE"
	case UserStatus_INACTIVE:
		return "INACTIVE"
	case UserStatus_BANNED:
		return "BANNED"
	}
	return "<UNSET>"
}

func UserStatusFromString(s string) (UserStatus, error) {
	switch s {
	case "US_NOT_SPECIFIED":
		return UserStatus_US_NOT_SPECIFIED, nil
	case "ACTIVE":
		return UserStatus_ACTIVE, nil
	case "INACTIVE":
		return UserStatus_INACTIVE, nil
	case "BANNED":
		return UserStatus_BANNED, nil
	}
	return UserStatus(0), fmt.Errorf("not a valid UserStatus string")
}

func UserStatusPtr(v UserStatus) *UserStatus { return &v }
func (p *UserStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = UserStatus(result.Int64)
	return
}

func (p *UserStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type UserEntity struct {
	Id   int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	User *User `thrift:"user,2" frugal:"2,default,User" json:"user"`
}

func NewUserEntity() *UserEntity {
	return &UserEntity{}
}

func (p *UserEntity) InitDefault() {
}

func (p *UserEntity) GetId() (v int64) {
	return p.Id
}

var UserEntity_User_DEFAULT *User

func (p *UserEntity) GetUser() (v *User) {
	if !p.IsSetUser() {
		return UserEntity_User_DEFAULT
	}
	return p.User
}
func (p *UserEntity) SetId(val int64) {
	p.Id = val
}
func (p *UserEntity) SetUser(val *User) {
	p.User = val
}

func (p *UserEntity) IsSetUser() bool {
	return p.User != nil
}

func (p *UserEntity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserEntity(%+v)", *p)
}

var fieldIDToName_UserEntity = map[int16]string{
	1: "id",
	2: "user",
}

type User struct {
	Email     string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Nickname  string `thrift:"nickname,2" frugal:"2,default,string" json:"nickname"`
	AvatarUrl string `thrift:"avatar_url,3" frugal:"3,default,string" json:"avatar_url"`
	CreatedAt int64  `thrift:"created_at,4" frugal:"4,default,i64" json:"created_at"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetNickname() (v string) {
	return p.Nickname
}

func (p *User) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *User) GetCreatedAt() (v int64) {
	return p.CreatedAt
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetNickname(val string) {
	p.Nickname = val
}
func (p *User) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *User) SetCreatedAt(val int64) {
	p.CreatedAt = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "email",
	2: "nickname",
	3: "avatar_url",
	4: "created_at",
}

type ResumeEntity struct {
	Id     int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Resume *Resume `thrift:"resume,2" frugal:"2,default,Resume" json:"resume"`
}

func NewResumeEntity() *ResumeEntity {
	return &ResumeEntity{}
}

func (p *ResumeEntity) InitDefault() {
}

func (p *ResumeEntity) GetId() (v int64) {
	return p.Id
}

var ResumeEntity_Resume_DEFAULT *Resume

func (p *ResumeEntity) GetResume() (v *Resume) {
	if !p.IsSetResume() {
		return ResumeEntity_Resume_DEFAULT
	}
	return p.Resume
}
func (p *ResumeEntity) SetId(val int64) {
	p.Id = val
}
func (p *ResumeEntity) SetResume(val *Resume) {
	p.Resume = val
}

func (p *ResumeEntity) IsSetResume() bool {
	return p.Resume != nil
}

func (p *ResumeEntity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResumeEntity(%+v)", *p)
}

var fieldIDToName_ResumeEntity = map[int16]string{
	1: "id",
	2: "resume",
}

type Resume struct {
	UserId        int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileUrl       string `thrift:"file_url,2" frugal:"2,default,string" json:"file_url"`
	ParsedContent string `thrift:"parsed_content,3" frugal:"3,default,string" json:"parsed_content"`
	CreatedAt     int64  `thrift:"created_at,4" frugal:"4,default,i64" json:"created_at"`
}

func NewResume() *Resume {
	return &Resume{}
}

func (p *Resume) InitDefault() {
}

func (p *Resume) GetUserId() (v int64) {
	return p.UserId
}

func (p *Resume) GetFileUrl() (v string) {
	return p.FileUrl
}

func (p *Resume) GetParsedContent() (v string) {
	return p.ParsedContent
}

func (p *Resume) GetCreatedAt() (v int64) {
	return p.CreatedAt
}
func (p *Resume) SetUserId(val int64) {
	p.UserId = val
}
func (p *Resume) SetFileUrl(val string) {
	p.FileUrl = val
}
func (p *Resume) SetParsedContent(val string) {
	p.ParsedContent = val
}
func (p *Resume) SetCreatedAt(val int64) {
	p.CreatedAt = val
}

func (p *Resume) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Resume(%+v)", *p)
}

var fieldIDToName_Resume = map[int16]string{
	1: "user_id",
	2: "file_url",
	3: "parsed_content",
	4: "created_at",
}
