// Code generated by hertz generator.

package user

import (
	"zpi/server/cmd/api/biz/router/common"
	"zpi/server/shared/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}
