// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlgen

import (
	"time"

	"gorm.io/gorm"
)

const TableNameQuestion = "questions"

// Question 题目表
type Question struct {
	ID          uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:题目ID" json:"id"`                                                           // 题目ID
	Title       string         `gorm:"column:title;type:varchar(200);not null;index:ft_title_content,priority:1;comment:题目标题" json:"title"`                                               // 题目标题
	Content     string         `gorm:"column:content;type:text;not null;index:ft_title_content,priority:2;comment:题目内容" json:"content"`                                                   // 题目内容
	Type        string         `gorm:"column:type;type:varchar(50);not null;index:idx_type,priority:1;comment:题目类型：coding-编程题，algorithm-算法题，system_design-系统设计" json:"type"`              // 题目类型：coding-编程题，algorithm-算法题，system_design-系统设计
	Category    *string        `gorm:"column:category;type:varchar(100);index:idx_category,priority:1;comment:题目分类" json:"category"`                                                      // 题目分类
	Difficulty  *string        `gorm:"column:difficulty;type:varchar(20);not null;index:idx_difficulty,priority:1;default:medium;comment:难度：easy-简单，medium-中等，hard-困难" json:"difficulty"` // 难度：easy-简单，medium-中等，hard-困难
	Tags        *string        `gorm:"column:tags;type:json;comment:标签（JSON数组）" json:"tags"`                                                                                              // 标签（JSON数组）
	Answer      *string        `gorm:"column:answer;type:text;comment:参考答案" json:"answer"`                                                                                                // 参考答案
	Hints       *string        `gorm:"column:hints;type:json;comment:提示（JSON数组）" json:"hints"`                                                                                            // 提示（JSON数组）
	TestCases   *string        `gorm:"column:test_cases;type:json;comment:测试用例（JSON数组）" json:"test_cases"`                                                                                // 测试用例（JSON数组）
	TimeLimit   *int32         `gorm:"column:time_limit;type:int(11);comment:时间限制（秒）" json:"time_limit"`                                                                                  // 时间限制（秒）
	MemoryLimit *int32         `gorm:"column:memory_limit;type:int(11);comment:内存限制（MB）" json:"memory_limit"`                                                                             // 内存限制（MB）
	PassRate    *float64       `gorm:"column:pass_rate;type:decimal(5,2);comment:通过率" json:"pass_rate"`                                                                                   // 通过率
	UsageCount  int32          `gorm:"column:usage_count;type:int(11);not null;comment:使用次数" json:"usage_count"`                                                                          // 使用次数
	Status      *int32         `gorm:"column:status;type:tinyint(4);not null;index:idx_status,priority:1;default:1;comment:状态：0-禁用，1-启用" json:"status"`                                   // 状态：0-禁用，1-启用
	CreatedBy   *uint64        `gorm:"column:created_by;type:bigint(20) unsigned;index:idx_created_by,priority:1;comment:创建者ID" json:"created_by"`                                        // 创建者ID
	CreatedAt   *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;autoCreateTime;comment:创建时间" json:"created_at"`                                  // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:更新时间" json:"updated_at"`                                  // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_deleted_at,priority:1;comment:删除时间（软删除）" json:"deleted_at"`                                               // 删除时间（软删除）
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
