// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confirmuploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuploadurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getabilityanalysisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _analyzeresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinterviewhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinterviewdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startinterviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interview_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitanswerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _finishinterviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _questionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoritequestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unfavoritequestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfavoritequestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getquestionlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getquestiondetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadresumeMw() []app.HandlerFunc {
	// your code...
	return nil
}
