// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"zpi/server/shared/kitex_gen/base"
)

type SendVerifyCodeRequest struct {
	CodeType base.VerifyCodeType    `thrift:"code_type,1" frugal:"1,default,VerifyCodeType" json:"code_type"`
	Purpose  base.VerifyCodePurpose `thrift:"purpose,2" frugal:"2,default,VerifyCodePurpose" json:"purpose"`
	Target   string                 `thrift:"target,3" frugal:"3,default,string" json:"target"`
}

func NewSendVerifyCodeRequest() *SendVerifyCodeRequest {
	return &SendVerifyCodeRequest{}
}

func (p *SendVerifyCodeRequest) InitDefault() {
}

func (p *SendVerifyCodeRequest) GetCodeType() (v base.VerifyCodeType) {
	return p.CodeType
}

func (p *SendVerifyCodeRequest) GetPurpose() (v base.VerifyCodePurpose) {
	return p.Purpose
}

func (p *SendVerifyCodeRequest) GetTarget() (v string) {
	return p.Target
}
func (p *SendVerifyCodeRequest) SetCodeType(val base.VerifyCodeType) {
	p.CodeType = val
}
func (p *SendVerifyCodeRequest) SetPurpose(val base.VerifyCodePurpose) {
	p.Purpose = val
}
func (p *SendVerifyCodeRequest) SetTarget(val string) {
	p.Target = val
}

func (p *SendVerifyCodeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendVerifyCodeRequest(%+v)", *p)
}

var fieldIDToName_SendVerifyCodeRequest = map[int16]string{
	1: "code_type",
	2: "purpose",
	3: "target",
}

type SendVerifyCodeResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewSendVerifyCodeResponse() *SendVerifyCodeResponse {
	return &SendVerifyCodeResponse{}
}

func (p *SendVerifyCodeResponse) InitDefault() {
}

var SendVerifyCodeResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *SendVerifyCodeResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return SendVerifyCodeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SendVerifyCodeResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *SendVerifyCodeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SendVerifyCodeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendVerifyCodeResponse(%+v)", *p)
}

var fieldIDToName_SendVerifyCodeResponse = map[int16]string{
	1: "base_resp",
}

type RegisterRequest struct {
	Email      *string `thrift:"email,1,optional" frugal:"1,optional,string" json:"email,omitempty"`
	Phone      *string `thrift:"phone,2,optional" frugal:"2,optional,string" json:"phone,omitempty"`
	Password   string  `thrift:"password,3" frugal:"3,default,string" json:"password"`
	Nickname   string  `thrift:"nickname,4" frugal:"4,default,string" json:"nickname"`
	VerifyCode string  `thrift:"verify_code,5" frugal:"5,default,string" json:"verify_code"`
	Username   *string `thrift:"username,6,optional" frugal:"6,optional,string" json:"username,omitempty"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

var RegisterRequest_Email_DEFAULT string

func (p *RegisterRequest) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return RegisterRequest_Email_DEFAULT
	}
	return *p.Email
}

var RegisterRequest_Phone_DEFAULT string

func (p *RegisterRequest) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return RegisterRequest_Phone_DEFAULT
	}
	return *p.Phone
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterRequest) GetNickname() (v string) {
	return p.Nickname
}

func (p *RegisterRequest) GetVerifyCode() (v string) {
	return p.VerifyCode
}

var RegisterRequest_Username_DEFAULT string

func (p *RegisterRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return RegisterRequest_Username_DEFAULT
	}
	return *p.Username
}
func (p *RegisterRequest) SetEmail(val *string) {
	p.Email = val
}
func (p *RegisterRequest) SetPhone(val *string) {
	p.Phone = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterRequest) SetNickname(val string) {
	p.Nickname = val
}
func (p *RegisterRequest) SetVerifyCode(val string) {
	p.VerifyCode = val
}
func (p *RegisterRequest) SetUsername(val *string) {
	p.Username = val
}

func (p *RegisterRequest) IsSetEmail() bool {
	return p.Email != nil
}

func (p *RegisterRequest) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *RegisterRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "email",
	2: "phone",
	3: "password",
	4: "nickname",
	5: "verify_code",
	6: "username",
}

type RegisterResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	UserId   int64              `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

var RegisterResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *RegisterResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return RegisterResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *RegisterResponse) GetUserId() (v int64) {
	return p.UserId
}
func (p *RegisterResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *RegisterResponse) SetUserId(val int64) {
	p.UserId = val
}

func (p *RegisterResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

var fieldIDToName_RegisterResponse = map[int16]string{
	1: "base_resp",
	2: "user_id",
}

type LoginRequest struct {
	Account    string  `thrift:"account,1" frugal:"1,default,string" json:"account"`
	Password   *string `thrift:"password,2,optional" frugal:"2,optional,string" json:"password,omitempty"`
	VerifyCode *string `thrift:"verify_code,3,optional" frugal:"3,optional,string" json:"verify_code,omitempty"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetAccount() (v string) {
	return p.Account
}

var LoginRequest_Password_DEFAULT string

func (p *LoginRequest) GetPassword() (v string) {
	if !p.IsSetPassword() {
		return LoginRequest_Password_DEFAULT
	}
	return *p.Password
}

var LoginRequest_VerifyCode_DEFAULT string

func (p *LoginRequest) GetVerifyCode() (v string) {
	if !p.IsSetVerifyCode() {
		return LoginRequest_VerifyCode_DEFAULT
	}
	return *p.VerifyCode
}
func (p *LoginRequest) SetAccount(val string) {
	p.Account = val
}
func (p *LoginRequest) SetPassword(val *string) {
	p.Password = val
}
func (p *LoginRequest) SetVerifyCode(val *string) {
	p.VerifyCode = val
}

func (p *LoginRequest) IsSetPassword() bool {
	return p.Password != nil
}

func (p *LoginRequest) IsSetVerifyCode() bool {
	return p.VerifyCode != nil
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "account",
	2: "password",
	3: "verify_code",
}

type LoginResponse struct {
	BaseResp   *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	Token      string             `thrift:"token,2" frugal:"2,default,string" json:"token"`
	UserEntity *base.UserEntity   `thrift:"user_entity,3" frugal:"3,default,base.UserEntity" json:"user_entity"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

var LoginResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *LoginResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return LoginResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *LoginResponse) GetToken() (v string) {
	return p.Token
}

var LoginResponse_UserEntity_DEFAULT *base.UserEntity

func (p *LoginResponse) GetUserEntity() (v *base.UserEntity) {
	if !p.IsSetUserEntity() {
		return LoginResponse_UserEntity_DEFAULT
	}
	return p.UserEntity
}
func (p *LoginResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *LoginResponse) SetToken(val string) {
	p.Token = val
}
func (p *LoginResponse) SetUserEntity(val *base.UserEntity) {
	p.UserEntity = val
}

func (p *LoginResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LoginResponse) IsSetUserEntity() bool {
	return p.UserEntity != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "base_resp",
	2: "token",
	3: "user_entity",
}

type LogoutRequest struct {
	UserId int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Token  string `thrift:"token,2" frugal:"2,default,string" json:"token"`
}

func NewLogoutRequest() *LogoutRequest {
	return &LogoutRequest{}
}

func (p *LogoutRequest) InitDefault() {
}

func (p *LogoutRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *LogoutRequest) GetToken() (v string) {
	return p.Token
}
func (p *LogoutRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *LogoutRequest) SetToken(val string) {
	p.Token = val
}

func (p *LogoutRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutRequest(%+v)", *p)
}

var fieldIDToName_LogoutRequest = map[int16]string{
	1: "user_id",
	2: "token",
}

type LogoutResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewLogoutResponse() *LogoutResponse {
	return &LogoutResponse{}
}

func (p *LogoutResponse) InitDefault() {
}

var LogoutResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *LogoutResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return LogoutResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *LogoutResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *LogoutResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LogoutResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutResponse(%+v)", *p)
}

var fieldIDToName_LogoutResponse = map[int16]string{
	1: "base_resp",
}

type DeleteAccountRequest struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewDeleteAccountRequest() *DeleteAccountRequest {
	return &DeleteAccountRequest{}
}

func (p *DeleteAccountRequest) InitDefault() {
}

func (p *DeleteAccountRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *DeleteAccountRequest) GetPassword() (v string) {
	return p.Password
}
func (p *DeleteAccountRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *DeleteAccountRequest) SetPassword(val string) {
	p.Password = val
}

func (p *DeleteAccountRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAccountRequest(%+v)", *p)
}

var fieldIDToName_DeleteAccountRequest = map[int16]string{
	1: "user_id",
	2: "password",
}

type DeleteAccountResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewDeleteAccountResponse() *DeleteAccountResponse {
	return &DeleteAccountResponse{}
}

func (p *DeleteAccountResponse) InitDefault() {
}

var DeleteAccountResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *DeleteAccountResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return DeleteAccountResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteAccountResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *DeleteAccountResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteAccountResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAccountResponse(%+v)", *p)
}

var fieldIDToName_DeleteAccountResponse = map[int16]string{
	1: "base_resp",
}

type GetUserRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserRequest() *GetUserRequest {
	return &GetUserRequest{}
}

func (p *GetUserRequest) InitDefault() {
}

func (p *GetUserRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRequest(%+v)", *p)
}

var fieldIDToName_GetUserRequest = map[int16]string{
	1: "user_id",
}

type GetUserResponse struct {
	BaseResp   *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	UserEntity *base.UserEntity   `thrift:"user_entity,2" frugal:"2,default,base.UserEntity" json:"user_entity"`
}

func NewGetUserResponse() *GetUserResponse {
	return &GetUserResponse{}
}

func (p *GetUserResponse) InitDefault() {
}

var GetUserResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetUserResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetUserResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetUserResponse_UserEntity_DEFAULT *base.UserEntity

func (p *GetUserResponse) GetUserEntity() (v *base.UserEntity) {
	if !p.IsSetUserEntity() {
		return GetUserResponse_UserEntity_DEFAULT
	}
	return p.UserEntity
}
func (p *GetUserResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetUserResponse) SetUserEntity(val *base.UserEntity) {
	p.UserEntity = val
}

func (p *GetUserResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserResponse) IsSetUserEntity() bool {
	return p.UserEntity != nil
}

func (p *GetUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResponse(%+v)", *p)
}

var fieldIDToName_GetUserResponse = map[int16]string{
	1: "base_resp",
	2: "user_entity",
}

type UpdateUserRequest struct {
	UserId    int64   `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Nickname  *string `thrift:"nickname,2,optional" frugal:"2,optional,string" json:"nickname,omitempty"`
	AvatarUrl *string `thrift:"avatar_url,3,optional" frugal:"3,optional,string" json:"avatar_url,omitempty"`
}

func NewUpdateUserRequest() *UpdateUserRequest {
	return &UpdateUserRequest{}
}

func (p *UpdateUserRequest) InitDefault() {
}

func (p *UpdateUserRequest) GetUserId() (v int64) {
	return p.UserId
}

var UpdateUserRequest_Nickname_DEFAULT string

func (p *UpdateUserRequest) GetNickname() (v string) {
	if !p.IsSetNickname() {
		return UpdateUserRequest_Nickname_DEFAULT
	}
	return *p.Nickname
}

var UpdateUserRequest_AvatarUrl_DEFAULT string

func (p *UpdateUserRequest) GetAvatarUrl() (v string) {
	if !p.IsSetAvatarUrl() {
		return UpdateUserRequest_AvatarUrl_DEFAULT
	}
	return *p.AvatarUrl
}
func (p *UpdateUserRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateUserRequest) SetNickname(val *string) {
	p.Nickname = val
}
func (p *UpdateUserRequest) SetAvatarUrl(val *string) {
	p.AvatarUrl = val
}

func (p *UpdateUserRequest) IsSetNickname() bool {
	return p.Nickname != nil
}

func (p *UpdateUserRequest) IsSetAvatarUrl() bool {
	return p.AvatarUrl != nil
}

func (p *UpdateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserRequest(%+v)", *p)
}

var fieldIDToName_UpdateUserRequest = map[int16]string{
	1: "user_id",
	2: "nickname",
	3: "avatar_url",
}

type UpdateUserResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewUpdateUserResponse() *UpdateUserResponse {
	return &UpdateUserResponse{}
}

func (p *UpdateUserResponse) InitDefault() {
}

var UpdateUserResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *UpdateUserResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return UpdateUserResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateUserResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *UpdateUserResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserResponse(%+v)", *p)
}

var fieldIDToName_UpdateUserResponse = map[int16]string{
	1: "base_resp",
}

type ChangePasswordRequest struct {
	UserId       int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	OldPassword  string `thrift:"old_password,2" frugal:"2,default,string" json:"old_password"`
	NewPassword_ string `thrift:"new_password,3" frugal:"3,default,string" json:"new_password"`
}

func NewChangePasswordRequest() *ChangePasswordRequest {
	return &ChangePasswordRequest{}
}

func (p *ChangePasswordRequest) InitDefault() {
}

func (p *ChangePasswordRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ChangePasswordRequest) GetOldPassword() (v string) {
	return p.OldPassword
}

func (p *ChangePasswordRequest) GetNewPassword_() (v string) {
	return p.NewPassword_
}
func (p *ChangePasswordRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ChangePasswordRequest) SetOldPassword(val string) {
	p.OldPassword = val
}
func (p *ChangePasswordRequest) SetNewPassword_(val string) {
	p.NewPassword_ = val
}

func (p *ChangePasswordRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangePasswordRequest(%+v)", *p)
}

var fieldIDToName_ChangePasswordRequest = map[int16]string{
	1: "user_id",
	2: "old_password",
	3: "new_password",
}

type ChangePasswordResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewChangePasswordResponse() *ChangePasswordResponse {
	return &ChangePasswordResponse{}
}

func (p *ChangePasswordResponse) InitDefault() {
}

var ChangePasswordResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *ChangePasswordResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return ChangePasswordResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ChangePasswordResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *ChangePasswordResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ChangePasswordResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangePasswordResponse(%+v)", *p)
}

var fieldIDToName_ChangePasswordResponse = map[int16]string{
	1: "base_resp",
}

type ResetPasswordRequest struct {
	Account      string `thrift:"account,1" frugal:"1,default,string" json:"account"`
	VerifyCode   string `thrift:"verify_code,2" frugal:"2,default,string" json:"verify_code"`
	NewPassword_ string `thrift:"new_password,3" frugal:"3,default,string" json:"new_password"`
}

func NewResetPasswordRequest() *ResetPasswordRequest {
	return &ResetPasswordRequest{}
}

func (p *ResetPasswordRequest) InitDefault() {
}

func (p *ResetPasswordRequest) GetAccount() (v string) {
	return p.Account
}

func (p *ResetPasswordRequest) GetVerifyCode() (v string) {
	return p.VerifyCode
}

func (p *ResetPasswordRequest) GetNewPassword_() (v string) {
	return p.NewPassword_
}
func (p *ResetPasswordRequest) SetAccount(val string) {
	p.Account = val
}
func (p *ResetPasswordRequest) SetVerifyCode(val string) {
	p.VerifyCode = val
}
func (p *ResetPasswordRequest) SetNewPassword_(val string) {
	p.NewPassword_ = val
}

func (p *ResetPasswordRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPasswordRequest(%+v)", *p)
}

var fieldIDToName_ResetPasswordRequest = map[int16]string{
	1: "account",
	2: "verify_code",
	3: "new_password",
}

type ResetPasswordResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewResetPasswordResponse() *ResetPasswordResponse {
	return &ResetPasswordResponse{}
}

func (p *ResetPasswordResponse) InitDefault() {
}

var ResetPasswordResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *ResetPasswordResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return ResetPasswordResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ResetPasswordResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *ResetPasswordResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ResetPasswordResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPasswordResponse(%+v)", *p)
}

var fieldIDToName_ResetPasswordResponse = map[int16]string{
	1: "base_resp",
}

type UploadResumeRequest struct {
	UserId        int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileUrl       string `thrift:"file_url,2" frugal:"2,default,string" json:"file_url"`
	ParsedContent string `thrift:"parsed_content,3" frugal:"3,default,string" json:"parsed_content"`
}

func NewUploadResumeRequest() *UploadResumeRequest {
	return &UploadResumeRequest{}
}

func (p *UploadResumeRequest) InitDefault() {
}

func (p *UploadResumeRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UploadResumeRequest) GetFileUrl() (v string) {
	return p.FileUrl
}

func (p *UploadResumeRequest) GetParsedContent() (v string) {
	return p.ParsedContent
}
func (p *UploadResumeRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UploadResumeRequest) SetFileUrl(val string) {
	p.FileUrl = val
}
func (p *UploadResumeRequest) SetParsedContent(val string) {
	p.ParsedContent = val
}

func (p *UploadResumeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadResumeRequest(%+v)", *p)
}

var fieldIDToName_UploadResumeRequest = map[int16]string{
	1: "user_id",
	2: "file_url",
	3: "parsed_content",
}

type UploadResumeResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	ResumeId int64              `thrift:"resume_id,2" frugal:"2,default,i64" json:"resume_id"`
}

func NewUploadResumeResponse() *UploadResumeResponse {
	return &UploadResumeResponse{}
}

func (p *UploadResumeResponse) InitDefault() {
}

var UploadResumeResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *UploadResumeResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return UploadResumeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *UploadResumeResponse) GetResumeId() (v int64) {
	return p.ResumeId
}
func (p *UploadResumeResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *UploadResumeResponse) SetResumeId(val int64) {
	p.ResumeId = val
}

func (p *UploadResumeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UploadResumeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadResumeResponse(%+v)", *p)
}

var fieldIDToName_UploadResumeResponse = map[int16]string{
	1: "base_resp",
	2: "resume_id",
}

type GetResumeRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetResumeRequest() *GetResumeRequest {
	return &GetResumeRequest{}
}

func (p *GetResumeRequest) InitDefault() {
}

func (p *GetResumeRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetResumeRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetResumeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetResumeRequest(%+v)", *p)
}

var fieldIDToName_GetResumeRequest = map[int16]string{
	1: "user_id",
}

type GetResumeResponse struct {
	BaseResp     *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	ResumeEntity *base.ResumeEntity `thrift:"resume_entity,2" frugal:"2,default,base.ResumeEntity" json:"resume_entity"`
}

func NewGetResumeResponse() *GetResumeResponse {
	return &GetResumeResponse{}
}

func (p *GetResumeResponse) InitDefault() {
}

var GetResumeResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetResumeResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetResumeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetResumeResponse_ResumeEntity_DEFAULT *base.ResumeEntity

func (p *GetResumeResponse) GetResumeEntity() (v *base.ResumeEntity) {
	if !p.IsSetResumeEntity() {
		return GetResumeResponse_ResumeEntity_DEFAULT
	}
	return p.ResumeEntity
}
func (p *GetResumeResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetResumeResponse) SetResumeEntity(val *base.ResumeEntity) {
	p.ResumeEntity = val
}

func (p *GetResumeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetResumeResponse) IsSetResumeEntity() bool {
	return p.ResumeEntity != nil
}

func (p *GetResumeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetResumeResponse(%+v)", *p)
}

var fieldIDToName_GetResumeResponse = map[int16]string{
	1: "base_resp",
	2: "resume_entity",
}

type DeleteResumeRequest struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ResumeId int64 `thrift:"resume_id,2" frugal:"2,default,i64" json:"resume_id"`
}

func NewDeleteResumeRequest() *DeleteResumeRequest {
	return &DeleteResumeRequest{}
}

func (p *DeleteResumeRequest) InitDefault() {
}

func (p *DeleteResumeRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *DeleteResumeRequest) GetResumeId() (v int64) {
	return p.ResumeId
}
func (p *DeleteResumeRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *DeleteResumeRequest) SetResumeId(val int64) {
	p.ResumeId = val
}

func (p *DeleteResumeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteResumeRequest(%+v)", *p)
}

var fieldIDToName_DeleteResumeRequest = map[int16]string{
	1: "user_id",
	2: "resume_id",
}

type DeleteResumeResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewDeleteResumeResponse() *DeleteResumeResponse {
	return &DeleteResumeResponse{}
}

func (p *DeleteResumeResponse) InitDefault() {
}

var DeleteResumeResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *DeleteResumeResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return DeleteResumeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteResumeResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *DeleteResumeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteResumeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteResumeResponse(%+v)", *p)
}

var fieldIDToName_DeleteResumeResponse = map[int16]string{
	1: "base_resp",
}

type UserService interface {
	HealthCheck(ctx context.Context) (r *base.HealthCheckResponse, err error)

	SendVerifyCode(ctx context.Context, req *SendVerifyCodeRequest) (r *SendVerifyCodeResponse, err error)

	Register(ctx context.Context, req *RegisterRequest) (r *RegisterResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	Logout(ctx context.Context, req *LogoutRequest) (r *LogoutResponse, err error)

	DeleteAccount(ctx context.Context, req *DeleteAccountRequest) (r *DeleteAccountResponse, err error)

	GetUser(ctx context.Context, req *GetUserRequest) (r *GetUserResponse, err error)

	UpdateUser(ctx context.Context, req *UpdateUserRequest) (r *UpdateUserResponse, err error)

	ChangePassword(ctx context.Context, req *ChangePasswordRequest) (r *ChangePasswordResponse, err error)

	ResetPassword(ctx context.Context, req *ResetPasswordRequest) (r *ResetPasswordResponse, err error)

	UploadResume(ctx context.Context, req *UploadResumeRequest) (r *UploadResumeResponse, err error)

	GetResume(ctx context.Context, req *GetResumeRequest) (r *GetResumeResponse, err error)

	DeleteResume(ctx context.Context, req *DeleteResumeRequest) (r *DeleteResumeResponse, err error)
}

type UserServiceHealthCheckArgs struct {
}

func NewUserServiceHealthCheckArgs() *UserServiceHealthCheckArgs {
	return &UserServiceHealthCheckArgs{}
}

func (p *UserServiceHealthCheckArgs) InitDefault() {
}

func (p *UserServiceHealthCheckArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceHealthCheckArgs(%+v)", *p)
}

var fieldIDToName_UserServiceHealthCheckArgs = map[int16]string{}

type UserServiceHealthCheckResult struct {
	Success *base.HealthCheckResponse `thrift:"success,0,optional" frugal:"0,optional,base.HealthCheckResponse" json:"success,omitempty"`
}

func NewUserServiceHealthCheckResult() *UserServiceHealthCheckResult {
	return &UserServiceHealthCheckResult{}
}

func (p *UserServiceHealthCheckResult) InitDefault() {
}

var UserServiceHealthCheckResult_Success_DEFAULT *base.HealthCheckResponse

func (p *UserServiceHealthCheckResult) GetSuccess() (v *base.HealthCheckResponse) {
	if !p.IsSetSuccess() {
		return UserServiceHealthCheckResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceHealthCheckResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.HealthCheckResponse)
}

func (p *UserServiceHealthCheckResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceHealthCheckResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceHealthCheckResult(%+v)", *p)
}

var fieldIDToName_UserServiceHealthCheckResult = map[int16]string{
	0: "success",
}

type UserServiceSendVerifyCodeArgs struct {
	Req *SendVerifyCodeRequest `thrift:"req,1" frugal:"1,default,SendVerifyCodeRequest" json:"req"`
}

func NewUserServiceSendVerifyCodeArgs() *UserServiceSendVerifyCodeArgs {
	return &UserServiceSendVerifyCodeArgs{}
}

func (p *UserServiceSendVerifyCodeArgs) InitDefault() {
}

var UserServiceSendVerifyCodeArgs_Req_DEFAULT *SendVerifyCodeRequest

func (p *UserServiceSendVerifyCodeArgs) GetReq() (v *SendVerifyCodeRequest) {
	if !p.IsSetReq() {
		return UserServiceSendVerifyCodeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceSendVerifyCodeArgs) SetReq(val *SendVerifyCodeRequest) {
	p.Req = val
}

func (p *UserServiceSendVerifyCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceSendVerifyCodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendVerifyCodeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSendVerifyCodeArgs = map[int16]string{
	1: "req",
}

type UserServiceSendVerifyCodeResult struct {
	Success *SendVerifyCodeResponse `thrift:"success,0,optional" frugal:"0,optional,SendVerifyCodeResponse" json:"success,omitempty"`
}

func NewUserServiceSendVerifyCodeResult() *UserServiceSendVerifyCodeResult {
	return &UserServiceSendVerifyCodeResult{}
}

func (p *UserServiceSendVerifyCodeResult) InitDefault() {
}

var UserServiceSendVerifyCodeResult_Success_DEFAULT *SendVerifyCodeResponse

func (p *UserServiceSendVerifyCodeResult) GetSuccess() (v *SendVerifyCodeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceSendVerifyCodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSendVerifyCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendVerifyCodeResponse)
}

func (p *UserServiceSendVerifyCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSendVerifyCodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendVerifyCodeResult(%+v)", *p)
}

var fieldIDToName_UserServiceSendVerifyCodeResult = map[int16]string{
	0: "success",
}

type UserServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterResponse" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResponse

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResponse) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResponse)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceLogoutArgs struct {
	Req *LogoutRequest `thrift:"req,1" frugal:"1,default,LogoutRequest" json:"req"`
}

func NewUserServiceLogoutArgs() *UserServiceLogoutArgs {
	return &UserServiceLogoutArgs{}
}

func (p *UserServiceLogoutArgs) InitDefault() {
}

var UserServiceLogoutArgs_Req_DEFAULT *LogoutRequest

func (p *UserServiceLogoutArgs) GetReq() (v *LogoutRequest) {
	if !p.IsSetReq() {
		return UserServiceLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLogoutArgs) SetReq(val *LogoutRequest) {
	p.Req = val
}

func (p *UserServiceLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutArgs = map[int16]string{
	1: "req",
}

type UserServiceLogoutResult struct {
	Success *LogoutResponse `thrift:"success,0,optional" frugal:"0,optional,LogoutResponse" json:"success,omitempty"`
}

func NewUserServiceLogoutResult() *UserServiceLogoutResult {
	return &UserServiceLogoutResult{}
}

func (p *UserServiceLogoutResult) InitDefault() {
}

var UserServiceLogoutResult_Success_DEFAULT *LogoutResponse

func (p *UserServiceLogoutResult) GetSuccess() (v *LogoutResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLogoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*LogoutResponse)
}

func (p *UserServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteAccountArgs struct {
	Req *DeleteAccountRequest `thrift:"req,1" frugal:"1,default,DeleteAccountRequest" json:"req"`
}

func NewUserServiceDeleteAccountArgs() *UserServiceDeleteAccountArgs {
	return &UserServiceDeleteAccountArgs{}
}

func (p *UserServiceDeleteAccountArgs) InitDefault() {
}

var UserServiceDeleteAccountArgs_Req_DEFAULT *DeleteAccountRequest

func (p *UserServiceDeleteAccountArgs) GetReq() (v *DeleteAccountRequest) {
	if !p.IsSetReq() {
		return UserServiceDeleteAccountArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteAccountArgs) SetReq(val *DeleteAccountRequest) {
	p.Req = val
}

func (p *UserServiceDeleteAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteAccountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteAccountArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteAccountArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteAccountResult struct {
	Success *DeleteAccountResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteAccountResponse" json:"success,omitempty"`
}

func NewUserServiceDeleteAccountResult() *UserServiceDeleteAccountResult {
	return &UserServiceDeleteAccountResult{}
}

func (p *UserServiceDeleteAccountResult) InitDefault() {
}

var UserServiceDeleteAccountResult_Success_DEFAULT *DeleteAccountResponse

func (p *UserServiceDeleteAccountResult) GetSuccess() (v *DeleteAccountResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteAccountResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAccountResponse)
}

func (p *UserServiceDeleteAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteAccountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteAccountResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteAccountResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
	Req *GetUserRequest `thrift:"req,1" frugal:"1,default,GetUserRequest" json:"req"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Req_DEFAULT *GetUserRequest

func (p *UserServiceGetUserArgs) GetReq() (v *GetUserRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserArgs) SetReq(val *GetUserRequest) {
	p.Req = val
}

func (p *UserServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserResult struct {
	Success *GetUserResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResponse)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserArgs struct {
	Req *UpdateUserRequest `thrift:"req,1" frugal:"1,default,UpdateUserRequest" json:"req"`
}

func NewUserServiceUpdateUserArgs() *UserServiceUpdateUserArgs {
	return &UserServiceUpdateUserArgs{}
}

func (p *UserServiceUpdateUserArgs) InitDefault() {
}

var UserServiceUpdateUserArgs_Req_DEFAULT *UpdateUserRequest

func (p *UserServiceUpdateUserArgs) GetReq() (v *UpdateUserRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserArgs) SetReq(val *UpdateUserRequest) {
	p.Req = val
}

func (p *UserServiceUpdateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserResult struct {
	Success *UpdateUserResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateUserResult() *UserServiceUpdateUserResult {
	return &UserServiceUpdateUserResult{}
}

func (p *UserServiceUpdateUserResult) InitDefault() {
}

var UserServiceUpdateUserResult_Success_DEFAULT *UpdateUserResponse

func (p *UserServiceUpdateUserResult) GetSuccess() (v *UpdateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResponse)
}

func (p *UserServiceUpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserResult = map[int16]string{
	0: "success",
}

type UserServiceChangePasswordArgs struct {
	Req *ChangePasswordRequest `thrift:"req,1" frugal:"1,default,ChangePasswordRequest" json:"req"`
}

func NewUserServiceChangePasswordArgs() *UserServiceChangePasswordArgs {
	return &UserServiceChangePasswordArgs{}
}

func (p *UserServiceChangePasswordArgs) InitDefault() {
}

var UserServiceChangePasswordArgs_Req_DEFAULT *ChangePasswordRequest

func (p *UserServiceChangePasswordArgs) GetReq() (v *ChangePasswordRequest) {
	if !p.IsSetReq() {
		return UserServiceChangePasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceChangePasswordArgs) SetReq(val *ChangePasswordRequest) {
	p.Req = val
}

func (p *UserServiceChangePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceChangePasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangePasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceChangePasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceChangePasswordResult struct {
	Success *ChangePasswordResponse `thrift:"success,0,optional" frugal:"0,optional,ChangePasswordResponse" json:"success,omitempty"`
}

func NewUserServiceChangePasswordResult() *UserServiceChangePasswordResult {
	return &UserServiceChangePasswordResult{}
}

func (p *UserServiceChangePasswordResult) InitDefault() {
}

var UserServiceChangePasswordResult_Success_DEFAULT *ChangePasswordResponse

func (p *UserServiceChangePasswordResult) GetSuccess() (v *ChangePasswordResponse) {
	if !p.IsSetSuccess() {
		return UserServiceChangePasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceChangePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChangePasswordResponse)
}

func (p *UserServiceChangePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceChangePasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangePasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceChangePasswordResult = map[int16]string{
	0: "success",
}

type UserServiceResetPasswordArgs struct {
	Req *ResetPasswordRequest `thrift:"req,1" frugal:"1,default,ResetPasswordRequest" json:"req"`
}

func NewUserServiceResetPasswordArgs() *UserServiceResetPasswordArgs {
	return &UserServiceResetPasswordArgs{}
}

func (p *UserServiceResetPasswordArgs) InitDefault() {
}

var UserServiceResetPasswordArgs_Req_DEFAULT *ResetPasswordRequest

func (p *UserServiceResetPasswordArgs) GetReq() (v *ResetPasswordRequest) {
	if !p.IsSetReq() {
		return UserServiceResetPasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceResetPasswordArgs) SetReq(val *ResetPasswordRequest) {
	p.Req = val
}

func (p *UserServiceResetPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceResetPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceResetPasswordResult struct {
	Success *ResetPasswordResponse `thrift:"success,0,optional" frugal:"0,optional,ResetPasswordResponse" json:"success,omitempty"`
}

func NewUserServiceResetPasswordResult() *UserServiceResetPasswordResult {
	return &UserServiceResetPasswordResult{}
}

func (p *UserServiceResetPasswordResult) InitDefault() {
}

var UserServiceResetPasswordResult_Success_DEFAULT *ResetPasswordResponse

func (p *UserServiceResetPasswordResult) GetSuccess() (v *ResetPasswordResponse) {
	if !p.IsSetSuccess() {
		return UserServiceResetPasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*ResetPasswordResponse)
}

func (p *UserServiceResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceResetPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordResult = map[int16]string{
	0: "success",
}

type UserServiceUploadResumeArgs struct {
	Req *UploadResumeRequest `thrift:"req,1" frugal:"1,default,UploadResumeRequest" json:"req"`
}

func NewUserServiceUploadResumeArgs() *UserServiceUploadResumeArgs {
	return &UserServiceUploadResumeArgs{}
}

func (p *UserServiceUploadResumeArgs) InitDefault() {
}

var UserServiceUploadResumeArgs_Req_DEFAULT *UploadResumeRequest

func (p *UserServiceUploadResumeArgs) GetReq() (v *UploadResumeRequest) {
	if !p.IsSetReq() {
		return UserServiceUploadResumeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUploadResumeArgs) SetReq(val *UploadResumeRequest) {
	p.Req = val
}

func (p *UserServiceUploadResumeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUploadResumeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadResumeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUploadResumeArgs = map[int16]string{
	1: "req",
}

type UserServiceUploadResumeResult struct {
	Success *UploadResumeResponse `thrift:"success,0,optional" frugal:"0,optional,UploadResumeResponse" json:"success,omitempty"`
}

func NewUserServiceUploadResumeResult() *UserServiceUploadResumeResult {
	return &UserServiceUploadResumeResult{}
}

func (p *UserServiceUploadResumeResult) InitDefault() {
}

var UserServiceUploadResumeResult_Success_DEFAULT *UploadResumeResponse

func (p *UserServiceUploadResumeResult) GetSuccess() (v *UploadResumeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUploadResumeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUploadResumeResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadResumeResponse)
}

func (p *UserServiceUploadResumeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUploadResumeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadResumeResult(%+v)", *p)
}

var fieldIDToName_UserServiceUploadResumeResult = map[int16]string{
	0: "success",
}

type UserServiceGetResumeArgs struct {
	Req *GetResumeRequest `thrift:"req,1" frugal:"1,default,GetResumeRequest" json:"req"`
}

func NewUserServiceGetResumeArgs() *UserServiceGetResumeArgs {
	return &UserServiceGetResumeArgs{}
}

func (p *UserServiceGetResumeArgs) InitDefault() {
}

var UserServiceGetResumeArgs_Req_DEFAULT *GetResumeRequest

func (p *UserServiceGetResumeArgs) GetReq() (v *GetResumeRequest) {
	if !p.IsSetReq() {
		return UserServiceGetResumeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetResumeArgs) SetReq(val *GetResumeRequest) {
	p.Req = val
}

func (p *UserServiceGetResumeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetResumeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetResumeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetResumeArgs = map[int16]string{
	1: "req",
}

type UserServiceGetResumeResult struct {
	Success *GetResumeResponse `thrift:"success,0,optional" frugal:"0,optional,GetResumeResponse" json:"success,omitempty"`
}

func NewUserServiceGetResumeResult() *UserServiceGetResumeResult {
	return &UserServiceGetResumeResult{}
}

func (p *UserServiceGetResumeResult) InitDefault() {
}

var UserServiceGetResumeResult_Success_DEFAULT *GetResumeResponse

func (p *UserServiceGetResumeResult) GetSuccess() (v *GetResumeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetResumeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetResumeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetResumeResponse)
}

func (p *UserServiceGetResumeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetResumeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetResumeResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetResumeResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteResumeArgs struct {
	Req *DeleteResumeRequest `thrift:"req,1" frugal:"1,default,DeleteResumeRequest" json:"req"`
}

func NewUserServiceDeleteResumeArgs() *UserServiceDeleteResumeArgs {
	return &UserServiceDeleteResumeArgs{}
}

func (p *UserServiceDeleteResumeArgs) InitDefault() {
}

var UserServiceDeleteResumeArgs_Req_DEFAULT *DeleteResumeRequest

func (p *UserServiceDeleteResumeArgs) GetReq() (v *DeleteResumeRequest) {
	if !p.IsSetReq() {
		return UserServiceDeleteResumeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteResumeArgs) SetReq(val *DeleteResumeRequest) {
	p.Req = val
}

func (p *UserServiceDeleteResumeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteResumeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteResumeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteResumeArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteResumeResult struct {
	Success *DeleteResumeResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteResumeResponse" json:"success,omitempty"`
}

func NewUserServiceDeleteResumeResult() *UserServiceDeleteResumeResult {
	return &UserServiceDeleteResumeResult{}
}

func (p *UserServiceDeleteResumeResult) InitDefault() {
}

var UserServiceDeleteResumeResult_Success_DEFAULT *DeleteResumeResponse

func (p *UserServiceDeleteResumeResult) GetSuccess() (v *DeleteResumeResponse) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteResumeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceDeleteResumeResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteResumeResponse)
}

func (p *UserServiceDeleteResumeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteResumeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteResumeResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteResumeResult = map[int16]string{
	0: "success",
}
