// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlentity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameInterview = "interviews"

// Interview 面试表
type Interview struct {
	ID          uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:面试ID" json:"id"`                                                                              // 面试ID
	UserID      uint64         `gorm:"column:user_id;type:bigint(20) unsigned;not null;index:idx_user_id,priority:1;comment:用户ID" json:"user_id"`                                                            // 用户ID
	Title       string         `gorm:"column:title;type:varchar(200);not null;comment:面试标题" json:"title"`                                                                                                    // 面试标题
	Description *string        `gorm:"column:description;type:text;comment:面试描述" json:"description"`                                                                                                         // 面试描述
	Type        string         `gorm:"column:type;type:varchar(50);not null;index:idx_type,priority:1;comment:面试类型：technical-技术面试，behavioral-行为面试" json:"type"`                                              // 面试类型：technical-技术面试，behavioral-行为面试
	Difficulty  string         `gorm:"column:difficulty;type:varchar(20);not null;default:medium;comment:难度：easy-简单，medium-中等，hard-困难" json:"difficulty"`                                                    // 难度：easy-简单，medium-中等，hard-困难
	Status      string         `gorm:"column:status;type:varchar(20);not null;index:idx_status,priority:1;default:pending;comment:状态：pending-待开始，in_progress-进行中，completed-已完成，cancelled-已取消" json:"status"` // 状态：pending-待开始，in_progress-进行中，completed-已完成，cancelled-已取消
	ScheduledAt *time.Time     `gorm:"column:scheduled_at;type:datetime;index:idx_scheduled_at,priority:1;comment:计划开始时间" json:"scheduled_at"`                                                               // 计划开始时间
	StartedAt   *time.Time     `gorm:"column:started_at;type:datetime;comment:实际开始时间" json:"started_at"`                                                                                                     // 实际开始时间
	CompletedAt *time.Time     `gorm:"column:completed_at;type:datetime;comment:完成时间" json:"completed_at"`                                                                                                   // 完成时间
	Duration    *int32         `gorm:"column:duration;type:int(11);comment:持续时间（秒）" json:"duration"`                                                                                                         // 持续时间（秒）
	Score       *float64       `gorm:"column:score;type:decimal(5,2);comment:评分" json:"score"`                                                                                                               // 评分
	Feedback    *string        `gorm:"column:feedback;type:text;comment:反馈" json:"feedback"`                                                                                                                 // 反馈
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;autoCreateTime;comment:创建时间" json:"created_at"`                                                     // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:更新时间" json:"updated_at"`                                                     // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_deleted_at,priority:1;comment:删除时间（软删除）" json:"deleted_at"`                                                                  // 删除时间（软删除）
}

// TableName Interview's table name
func (*Interview) TableName() string {
	return TableNameInterview
}
