// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlentity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameResume = "resumes"

// Resume 简历表
type Resume struct {
	ID            uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:简历ID" json:"id"`                                                          // 简历ID
	UserID        uint64         `gorm:"column:user_id;type:bigint(20) unsigned;not null;index:idx_user_id,priority:1;comment:用户ID" json:"user_id"`                                        // 用户ID
	FileURL       string         `gorm:"column:file_url;type:varchar(500);not null;comment:简历文件URL" json:"file_url"`                                                                       // 简历文件URL
	ParsedContent *string        `gorm:"column:parsed_content;type:text;comment:解析后的简历内容（JSON格式）" json:"parsed_content"`                                                                   // 解析后的简历内容（JSON格式）
	FileName      *string        `gorm:"column:file_name;type:varchar(255);comment:原始文件名" json:"file_name"`                                                                                // 原始文件名
	FileSize      *int64         `gorm:"column:file_size;type:bigint(20);comment:文件大小（字节）" json:"file_size"`                                                                               // 文件大小（字节）
	FileType      *string        `gorm:"column:file_type;type:varchar(50);comment:文件类型（pdf/doc/docx等）" json:"file_type"`                                                                   // 文件类型（pdf/doc/docx等）
	ParseStatus   int32          `gorm:"column:parse_status;type:tinyint(4);not null;index:idx_parse_status,priority:1;comment:解析状态：0-未解析，1-解析中，2-解析成功，3-解析失败" json:"parse_status"`        // 解析状态：0-未解析，1-解析中，2-解析成功，3-解析失败
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime;not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:更新时间" json:"updated_at"`                                 // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_deleted_at,priority:1;comment:删除时间（软删除）" json:"deleted_at"`                                              // 删除时间（软删除）
}

// TableName Resume's table name
func (*Resume) TableName() string {
	return TableNameResume
}
