-- 题目表
CREATE TABLE IF NOT EXISTS `questions` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '题目ID',
    `title` VARCHAR(200) NOT NULL COMMENT '题目标题',
    `content` TEXT NOT NULL COMMENT '题目内容',
    `type` VARCHAR(50) NOT NULL COMMENT '题目类型：coding-编程题，algorithm-算法题，system_design-系统设计',
    `category` VARCHAR(100) DEFAULT NULL COMMENT '题目分类',
    `difficulty` VARCHAR(20) NOT NULL DEFAULT 'medium' COMMENT '难度：easy-简单，medium-中等，hard-困难',
    `tags` JSON DEFAULT NULL COMMENT '标签（JSON数组）',
    `answer` TEXT DEFAULT NULL COMMENT '参考答案',
    `hints` JSON DEFAULT NULL COMMENT '提示（JSON数组）',
    `test_cases` JSON DEFAULT NULL COMMENT '测试用例（JSON数组）',
    `time_limit` INT DEFAULT NULL COMMENT '时间限制（秒）',
    `memory_limit` INT DEFAULT NULL COMMENT '内存限制（MB）',
    `pass_rate` DECIMAL(5,2) DEFAULT NULL COMMENT '通过率',
    `usage_count` INT NOT NULL DEFAULT 0 COMMENT '使用次数',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建者ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间（软删除）',
    PRIMARY KEY (`id`),
    KEY `idx_type` (`type`),
    KEY `idx_category` (`category`),
    KEY `idx_difficulty` (`difficulty`),
    KEY `idx_status` (`status`),
    KEY `idx_created_by` (`created_by`),
    KEY `idx_deleted_at` (`deleted_at`),
    FULLTEXT KEY `ft_title_content` (`title`, `content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='题目表';