-- 存储表
CREATE TABLE IF NOT EXISTS `storage` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '存储ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    `file_name` VARCHAR(255) NOT NULL COMMENT '文件名',
    `file_path` VARCHAR(500) NOT NULL COMMENT '文件路径',
    `file_size` BIGINT NOT NULL COMMENT '文件大小（字节）',
    `file_type` VARCHAR(100) NOT NULL COMMENT '文件类型（MIME类型）',
    `file_ext` VARCHAR(20) DEFAULT NULL COMMENT '文件扩展名',
    `storage_type` VARCHAR(50) NOT NULL DEFAULT 'local' COMMENT '存储类型：local-本地，oss-对象存储，s3-S3',
    `bucket` VARCHAR(100) DEFAULT NULL COMMENT '存储桶名称',
    `object_key` VARCHAR(500) DEFAULT NULL COMMENT '对象键',
    `url` VARCHAR(1000) DEFAULT NULL COMMENT '访问URL',
    `thumbnail_url` VARCHAR(1000) DEFAULT NULL COMMENT '缩略图URL',
    `md5` VARCHAR(32) DEFAULT NULL COMMENT 'MD5哈希值',
    `sha256` VARCHAR(64) DEFAULT NULL COMMENT 'SHA256哈希值',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-已删除，1-正常',
    `upload_ip` VARCHAR(45) DEFAULT NULL COMMENT '上传IP',
    `download_count` INT NOT NULL DEFAULT 0 COMMENT '下载次数',
    `metadata` JSON DEFAULT NULL COMMENT '元数据（JSON）',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间（软删除）',
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_file_type` (`file_type`),
    KEY `idx_storage_type` (`storage_type`),
    KEY `idx_md5` (`md5`),
    KEY `idx_status` (`status`),
    KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='存储表';