// Code generated by hertz generator.

package storage

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	storage "zpi/server/cmd/api/biz/model/storage"
)

// GetUploadUrl .
// @router /api/v1/file/upload-url [GET]
func GetUploadUrl(ctx context.Context, c *app.RequestContext) {
	var err error
	var req storage.GetUploadUrlRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(storage.GetUploadUrlResponse)

	c.JSON(consts.StatusOK, resp)
}

// ConfirmUpload .
// @router /api/v1/file/confirm [POST]
func ConfirmUpload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req storage.ConfirmUploadRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(storage.ConfirmUploadResponse)

	c.JSON(consts.StatusOK, resp)
}
