// Code generated by hertz generator.

package interview

import (
	"zpi/server/cmd/api/biz/router/common"
	"zpi/server/shared/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return common.CommonMW()
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _v1Mw() []app.HandlerFunc {
	return nil
}

func _interviewMw() []app.HandlerFunc {
	// 面试相关接口需要认证
	return []app.HandlerFunc{common.PasetoAuth(consts.User)}
}

func _getabilityanalysisMw() []app.HandlerFunc {
	return nil
}

func _analyzeresumeMw() []app.HandlerFunc {
	return nil
}

func _getinterviewhistoryMw() []app.HandlerFunc {
	return nil
}

func _getinterviewdetailMw() []app.HandlerFunc {
	return nil
}

func _startinterviewMw() []app.HandlerFunc {
	return nil
}

func _interview_idMw() []app.HandlerFunc {
	return nil
}

func _submitanswerMw() []app.HandlerFunc {
	return nil
}

func _finishinterviewMw() []app.HandlerFunc {
	return nil
}
