// Code generated by hertz generator.

package main

import (
	"context"
	"net/http"
	handler "zpi/server/cmd/api/biz/handler"
	"zpi/server/shared/errno"
	"zpi/server/shared/tools"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) {
		c.JSON(http.StatusNotFound, tools.BuildBaseResp(errno.NoRoute))
	})

	r.NoMethod(func(ctx context.Context, c *app.RequestContext) {
		c.JSON(http.StatusMethodNotAllowed, tools.BuildBaseResp(errno.NoMethod))
	})
}
