// Code generated by hertz generator.

package storage

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confirmuploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuploadurlMw() []app.HandlerFunc {
	// your code...
	return nil
}
