// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package interview

import (
	"context"
	"fmt"
	"zpi/server/shared/kitex_gen/base"
)

type StartInterviewRequest struct {
	UserId     int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Type       int32  `thrift:"type,2" frugal:"2,default,i32" json:"type"`
	Category   string `thrift:"category,3" frugal:"3,default,string" json:"category"`
	Difficulty int32  `thrift:"difficulty,4" frugal:"4,default,i32" json:"difficulty"`
	Round      int32  `thrift:"round,5" frugal:"5,default,i32" json:"round"`
	ResumeId   int64  `thrift:"resume_id,6" frugal:"6,default,i64" json:"resume_id"`
}

func NewStartInterviewRequest() *StartInterviewRequest {
	return &StartInterviewRequest{}
}

func (p *StartInterviewRequest) InitDefault() {
}

func (p *StartInterviewRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *StartInterviewRequest) GetType() (v int32) {
	return p.Type
}

func (p *StartInterviewRequest) GetCategory() (v string) {
	return p.Category
}

func (p *StartInterviewRequest) GetDifficulty() (v int32) {
	return p.Difficulty
}

func (p *StartInterviewRequest) GetRound() (v int32) {
	return p.Round
}

func (p *StartInterviewRequest) GetResumeId() (v int64) {
	return p.ResumeId
}
func (p *StartInterviewRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *StartInterviewRequest) SetType(val int32) {
	p.Type = val
}
func (p *StartInterviewRequest) SetCategory(val string) {
	p.Category = val
}
func (p *StartInterviewRequest) SetDifficulty(val int32) {
	p.Difficulty = val
}
func (p *StartInterviewRequest) SetRound(val int32) {
	p.Round = val
}
func (p *StartInterviewRequest) SetResumeId(val int64) {
	p.ResumeId = val
}

func (p *StartInterviewRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartInterviewRequest(%+v)", *p)
}

var fieldIDToName_StartInterviewRequest = map[int16]string{
	1: "user_id",
	2: "type",
	3: "category",
	4: "difficulty",
	5: "round",
	6: "resume_id",
}

type StartInterviewResponse struct {
	BaseResp      *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	InterviewId   int64              `thrift:"interview_id,2" frugal:"2,default,i64" json:"interview_id"`
	FirstQuestion string             `thrift:"first_question,3" frugal:"3,default,string" json:"first_question"`
}

func NewStartInterviewResponse() *StartInterviewResponse {
	return &StartInterviewResponse{}
}

func (p *StartInterviewResponse) InitDefault() {
}

var StartInterviewResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *StartInterviewResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return StartInterviewResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *StartInterviewResponse) GetInterviewId() (v int64) {
	return p.InterviewId
}

func (p *StartInterviewResponse) GetFirstQuestion() (v string) {
	return p.FirstQuestion
}
func (p *StartInterviewResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *StartInterviewResponse) SetInterviewId(val int64) {
	p.InterviewId = val
}
func (p *StartInterviewResponse) SetFirstQuestion(val string) {
	p.FirstQuestion = val
}

func (p *StartInterviewResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *StartInterviewResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartInterviewResponse(%+v)", *p)
}

var fieldIDToName_StartInterviewResponse = map[int16]string{
	1: "base_resp",
	2: "interview_id",
	3: "first_question",
}

type SubmitAnswerRequest struct {
	InterviewId int64  `thrift:"interview_id,1" frugal:"1,default,i64" json:"interview_id"`
	UserId      int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Answer      string `thrift:"answer,3" frugal:"3,default,string" json:"answer"`
}

func NewSubmitAnswerRequest() *SubmitAnswerRequest {
	return &SubmitAnswerRequest{}
}

func (p *SubmitAnswerRequest) InitDefault() {
}

func (p *SubmitAnswerRequest) GetInterviewId() (v int64) {
	return p.InterviewId
}

func (p *SubmitAnswerRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *SubmitAnswerRequest) GetAnswer() (v string) {
	return p.Answer
}
func (p *SubmitAnswerRequest) SetInterviewId(val int64) {
	p.InterviewId = val
}
func (p *SubmitAnswerRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *SubmitAnswerRequest) SetAnswer(val string) {
	p.Answer = val
}

func (p *SubmitAnswerRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubmitAnswerRequest(%+v)", *p)
}

var fieldIDToName_SubmitAnswerRequest = map[int16]string{
	1: "interview_id",
	2: "user_id",
	3: "answer",
}

type SubmitAnswerResponse struct {
	BaseResp     *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	NextQuestion string             `thrift:"next_question,2" frugal:"2,default,string" json:"next_question"`
	IsFinished   bool               `thrift:"is_finished,3" frugal:"3,default,bool" json:"is_finished"`
}

func NewSubmitAnswerResponse() *SubmitAnswerResponse {
	return &SubmitAnswerResponse{}
}

func (p *SubmitAnswerResponse) InitDefault() {
}

var SubmitAnswerResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *SubmitAnswerResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return SubmitAnswerResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *SubmitAnswerResponse) GetNextQuestion() (v string) {
	return p.NextQuestion
}

func (p *SubmitAnswerResponse) GetIsFinished() (v bool) {
	return p.IsFinished
}
func (p *SubmitAnswerResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *SubmitAnswerResponse) SetNextQuestion(val string) {
	p.NextQuestion = val
}
func (p *SubmitAnswerResponse) SetIsFinished(val bool) {
	p.IsFinished = val
}

func (p *SubmitAnswerResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SubmitAnswerResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubmitAnswerResponse(%+v)", *p)
}

var fieldIDToName_SubmitAnswerResponse = map[int16]string{
	1: "base_resp",
	2: "next_question",
	3: "is_finished",
}

type FinishInterviewRequest struct {
	InterviewId int64 `thrift:"interview_id,1" frugal:"1,default,i64" json:"interview_id"`
	UserId      int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewFinishInterviewRequest() *FinishInterviewRequest {
	return &FinishInterviewRequest{}
}

func (p *FinishInterviewRequest) InitDefault() {
}

func (p *FinishInterviewRequest) GetInterviewId() (v int64) {
	return p.InterviewId
}

func (p *FinishInterviewRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *FinishInterviewRequest) SetInterviewId(val int64) {
	p.InterviewId = val
}
func (p *FinishInterviewRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *FinishInterviewRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FinishInterviewRequest(%+v)", *p)
}

var fieldIDToName_FinishInterviewRequest = map[int16]string{
	1: "interview_id",
	2: "user_id",
}

type FinishInterviewResponse struct {
	BaseResp   *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	Score      int32              `thrift:"score,2" frugal:"2,default,i32" json:"score"`
	Evaluation string             `thrift:"evaluation,3" frugal:"3,default,string" json:"evaluation"`
}

func NewFinishInterviewResponse() *FinishInterviewResponse {
	return &FinishInterviewResponse{}
}

func (p *FinishInterviewResponse) InitDefault() {
}

var FinishInterviewResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *FinishInterviewResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return FinishInterviewResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *FinishInterviewResponse) GetScore() (v int32) {
	return p.Score
}

func (p *FinishInterviewResponse) GetEvaluation() (v string) {
	return p.Evaluation
}
func (p *FinishInterviewResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *FinishInterviewResponse) SetScore(val int32) {
	p.Score = val
}
func (p *FinishInterviewResponse) SetEvaluation(val string) {
	p.Evaluation = val
}

func (p *FinishInterviewResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FinishInterviewResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FinishInterviewResponse(%+v)", *p)
}

var fieldIDToName_FinishInterviewResponse = map[int16]string{
	1: "base_resp",
	2: "score",
	3: "evaluation",
}

type GetInterviewDetailRequest struct {
	InterviewId int64 `thrift:"interview_id,1" frugal:"1,default,i64" json:"interview_id"`
	UserId      int64 `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewGetInterviewDetailRequest() *GetInterviewDetailRequest {
	return &GetInterviewDetailRequest{}
}

func (p *GetInterviewDetailRequest) InitDefault() {
}

func (p *GetInterviewDetailRequest) GetInterviewId() (v int64) {
	return p.InterviewId
}

func (p *GetInterviewDetailRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetInterviewDetailRequest) SetInterviewId(val int64) {
	p.InterviewId = val
}
func (p *GetInterviewDetailRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetInterviewDetailRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetInterviewDetailRequest(%+v)", *p)
}

var fieldIDToName_GetInterviewDetailRequest = map[int16]string{
	1: "interview_id",
	2: "user_id",
}

type GetInterviewDetailResponse struct {
	BaseResp        *base.BaseResponse       `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	InterviewEntity *base.InterviewEntity    `thrift:"interview_entity,2" frugal:"2,default,base.InterviewEntity" json:"interview_entity"`
	Messages        []*base.InterviewMessage `thrift:"messages,3" frugal:"3,default,list<base.InterviewMessage>" json:"messages"`
}

func NewGetInterviewDetailResponse() *GetInterviewDetailResponse {
	return &GetInterviewDetailResponse{}
}

func (p *GetInterviewDetailResponse) InitDefault() {
}

var GetInterviewDetailResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetInterviewDetailResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetInterviewDetailResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetInterviewDetailResponse_InterviewEntity_DEFAULT *base.InterviewEntity

func (p *GetInterviewDetailResponse) GetInterviewEntity() (v *base.InterviewEntity) {
	if !p.IsSetInterviewEntity() {
		return GetInterviewDetailResponse_InterviewEntity_DEFAULT
	}
	return p.InterviewEntity
}

func (p *GetInterviewDetailResponse) GetMessages() (v []*base.InterviewMessage) {
	return p.Messages
}
func (p *GetInterviewDetailResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetInterviewDetailResponse) SetInterviewEntity(val *base.InterviewEntity) {
	p.InterviewEntity = val
}
func (p *GetInterviewDetailResponse) SetMessages(val []*base.InterviewMessage) {
	p.Messages = val
}

func (p *GetInterviewDetailResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetInterviewDetailResponse) IsSetInterviewEntity() bool {
	return p.InterviewEntity != nil
}

func (p *GetInterviewDetailResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetInterviewDetailResponse(%+v)", *p)
}

var fieldIDToName_GetInterviewDetailResponse = map[int16]string{
	1: "base_resp",
	2: "interview_entity",
	3: "messages",
}

type GetInterviewHistoryRequest struct {
	UserId int64             `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Type   int32             `thrift:"type,2" frugal:"2,default,i32" json:"type"`
	Page   *base.PageRequest `thrift:"page,3" frugal:"3,default,base.PageRequest" json:"page"`
}

func NewGetInterviewHistoryRequest() *GetInterviewHistoryRequest {
	return &GetInterviewHistoryRequest{}
}

func (p *GetInterviewHistoryRequest) InitDefault() {
}

func (p *GetInterviewHistoryRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetInterviewHistoryRequest) GetType() (v int32) {
	return p.Type
}

var GetInterviewHistoryRequest_Page_DEFAULT *base.PageRequest

func (p *GetInterviewHistoryRequest) GetPage() (v *base.PageRequest) {
	if !p.IsSetPage() {
		return GetInterviewHistoryRequest_Page_DEFAULT
	}
	return p.Page
}
func (p *GetInterviewHistoryRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetInterviewHistoryRequest) SetType(val int32) {
	p.Type = val
}
func (p *GetInterviewHistoryRequest) SetPage(val *base.PageRequest) {
	p.Page = val
}

func (p *GetInterviewHistoryRequest) IsSetPage() bool {
	return p.Page != nil
}

func (p *GetInterviewHistoryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetInterviewHistoryRequest(%+v)", *p)
}

var fieldIDToName_GetInterviewHistoryRequest = map[int16]string{
	1: "user_id",
	2: "type",
	3: "page",
}

type GetInterviewHistoryResponse struct {
	BaseResp   *base.BaseResponse      `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	Interviews []*base.InterviewEntity `thrift:"interviews,2" frugal:"2,default,list<base.InterviewEntity>" json:"interviews"`
	Page       *base.PageResponse      `thrift:"page,3" frugal:"3,default,base.PageResponse" json:"page"`
}

func NewGetInterviewHistoryResponse() *GetInterviewHistoryResponse {
	return &GetInterviewHistoryResponse{}
}

func (p *GetInterviewHistoryResponse) InitDefault() {
}

var GetInterviewHistoryResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetInterviewHistoryResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetInterviewHistoryResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetInterviewHistoryResponse) GetInterviews() (v []*base.InterviewEntity) {
	return p.Interviews
}

var GetInterviewHistoryResponse_Page_DEFAULT *base.PageResponse

func (p *GetInterviewHistoryResponse) GetPage() (v *base.PageResponse) {
	if !p.IsSetPage() {
		return GetInterviewHistoryResponse_Page_DEFAULT
	}
	return p.Page
}
func (p *GetInterviewHistoryResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetInterviewHistoryResponse) SetInterviews(val []*base.InterviewEntity) {
	p.Interviews = val
}
func (p *GetInterviewHistoryResponse) SetPage(val *base.PageResponse) {
	p.Page = val
}

func (p *GetInterviewHistoryResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetInterviewHistoryResponse) IsSetPage() bool {
	return p.Page != nil
}

func (p *GetInterviewHistoryResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetInterviewHistoryResponse(%+v)", *p)
}

var fieldIDToName_GetInterviewHistoryResponse = map[int16]string{
	1: "base_resp",
	2: "interviews",
	3: "page",
}

type AnalyzeResumeRequest struct {
	UserId   int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	ResumeId int64 `thrift:"resume_id,2" frugal:"2,default,i64" json:"resume_id"`
}

func NewAnalyzeResumeRequest() *AnalyzeResumeRequest {
	return &AnalyzeResumeRequest{}
}

func (p *AnalyzeResumeRequest) InitDefault() {
}

func (p *AnalyzeResumeRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *AnalyzeResumeRequest) GetResumeId() (v int64) {
	return p.ResumeId
}
func (p *AnalyzeResumeRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *AnalyzeResumeRequest) SetResumeId(val int64) {
	p.ResumeId = val
}

func (p *AnalyzeResumeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyzeResumeRequest(%+v)", *p)
}

var fieldIDToName_AnalyzeResumeRequest = map[int16]string{
	1: "user_id",
	2: "resume_id",
}

type AnalyzeResumeResponse struct {
	BaseResp         *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	Analysis         string             `thrift:"analysis,2" frugal:"2,default,string" json:"analysis"`
	Suggestions      []string           `thrift:"suggestions,3" frugal:"3,default,list<string>" json:"suggestions"`
	MatchedPositions []string           `thrift:"matched_positions,4" frugal:"4,default,list<string>" json:"matched_positions"`
}

func NewAnalyzeResumeResponse() *AnalyzeResumeResponse {
	return &AnalyzeResumeResponse{}
}

func (p *AnalyzeResumeResponse) InitDefault() {
}

var AnalyzeResumeResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *AnalyzeResumeResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return AnalyzeResumeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *AnalyzeResumeResponse) GetAnalysis() (v string) {
	return p.Analysis
}

func (p *AnalyzeResumeResponse) GetSuggestions() (v []string) {
	return p.Suggestions
}

func (p *AnalyzeResumeResponse) GetMatchedPositions() (v []string) {
	return p.MatchedPositions
}
func (p *AnalyzeResumeResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *AnalyzeResumeResponse) SetAnalysis(val string) {
	p.Analysis = val
}
func (p *AnalyzeResumeResponse) SetSuggestions(val []string) {
	p.Suggestions = val
}
func (p *AnalyzeResumeResponse) SetMatchedPositions(val []string) {
	p.MatchedPositions = val
}

func (p *AnalyzeResumeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *AnalyzeResumeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AnalyzeResumeResponse(%+v)", *p)
}

var fieldIDToName_AnalyzeResumeResponse = map[int16]string{
	1: "base_resp",
	2: "analysis",
	3: "suggestions",
	4: "matched_positions",
}

type GetAbilityAnalysisRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetAbilityAnalysisRequest() *GetAbilityAnalysisRequest {
	return &GetAbilityAnalysisRequest{}
}

func (p *GetAbilityAnalysisRequest) InitDefault() {
}

func (p *GetAbilityAnalysisRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetAbilityAnalysisRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetAbilityAnalysisRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAbilityAnalysisRequest(%+v)", *p)
}

var fieldIDToName_GetAbilityAnalysisRequest = map[int16]string{
	1: "user_id",
}

type GetAbilityAnalysisResponse struct {
	BaseResp  *base.BaseResponse   `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	Abilities []*base.AbilityScore `thrift:"abilities,2" frugal:"2,default,list<base.AbilityScore>" json:"abilities"`
	Summary   string               `thrift:"summary,3" frugal:"3,default,string" json:"summary"`
}

func NewGetAbilityAnalysisResponse() *GetAbilityAnalysisResponse {
	return &GetAbilityAnalysisResponse{}
}

func (p *GetAbilityAnalysisResponse) InitDefault() {
}

var GetAbilityAnalysisResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetAbilityAnalysisResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetAbilityAnalysisResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetAbilityAnalysisResponse) GetAbilities() (v []*base.AbilityScore) {
	return p.Abilities
}

func (p *GetAbilityAnalysisResponse) GetSummary() (v string) {
	return p.Summary
}
func (p *GetAbilityAnalysisResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetAbilityAnalysisResponse) SetAbilities(val []*base.AbilityScore) {
	p.Abilities = val
}
func (p *GetAbilityAnalysisResponse) SetSummary(val string) {
	p.Summary = val
}

func (p *GetAbilityAnalysisResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetAbilityAnalysisResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAbilityAnalysisResponse(%+v)", *p)
}

var fieldIDToName_GetAbilityAnalysisResponse = map[int16]string{
	1: "base_resp",
	2: "abilities",
	3: "summary",
}

type InterviewService interface {
	StartInterview(ctx context.Context, req *StartInterviewRequest) (r *StartInterviewResponse, err error)

	SubmitAnswer(ctx context.Context, req *SubmitAnswerRequest) (r *SubmitAnswerResponse, err error)

	FinishInterview(ctx context.Context, req *FinishInterviewRequest) (r *FinishInterviewResponse, err error)

	GetInterviewDetail(ctx context.Context, req *GetInterviewDetailRequest) (r *GetInterviewDetailResponse, err error)

	GetInterviewHistory(ctx context.Context, req *GetInterviewHistoryRequest) (r *GetInterviewHistoryResponse, err error)

	AnalyzeResume(ctx context.Context, req *AnalyzeResumeRequest) (r *AnalyzeResumeResponse, err error)

	GetAbilityAnalysis(ctx context.Context, req *GetAbilityAnalysisRequest) (r *GetAbilityAnalysisResponse, err error)
}

type InterviewServiceStartInterviewArgs struct {
	Req *StartInterviewRequest `thrift:"req,1" frugal:"1,default,StartInterviewRequest" json:"req"`
}

func NewInterviewServiceStartInterviewArgs() *InterviewServiceStartInterviewArgs {
	return &InterviewServiceStartInterviewArgs{}
}

func (p *InterviewServiceStartInterviewArgs) InitDefault() {
}

var InterviewServiceStartInterviewArgs_Req_DEFAULT *StartInterviewRequest

func (p *InterviewServiceStartInterviewArgs) GetReq() (v *StartInterviewRequest) {
	if !p.IsSetReq() {
		return InterviewServiceStartInterviewArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceStartInterviewArgs) SetReq(val *StartInterviewRequest) {
	p.Req = val
}

func (p *InterviewServiceStartInterviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceStartInterviewArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceStartInterviewArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceStartInterviewArgs = map[int16]string{
	1: "req",
}

type InterviewServiceStartInterviewResult struct {
	Success *StartInterviewResponse `thrift:"success,0,optional" frugal:"0,optional,StartInterviewResponse" json:"success,omitempty"`
}

func NewInterviewServiceStartInterviewResult() *InterviewServiceStartInterviewResult {
	return &InterviewServiceStartInterviewResult{}
}

func (p *InterviewServiceStartInterviewResult) InitDefault() {
}

var InterviewServiceStartInterviewResult_Success_DEFAULT *StartInterviewResponse

func (p *InterviewServiceStartInterviewResult) GetSuccess() (v *StartInterviewResponse) {
	if !p.IsSetSuccess() {
		return InterviewServiceStartInterviewResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceStartInterviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*StartInterviewResponse)
}

func (p *InterviewServiceStartInterviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceStartInterviewResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceStartInterviewResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceStartInterviewResult = map[int16]string{
	0: "success",
}

type InterviewServiceSubmitAnswerArgs struct {
	Req *SubmitAnswerRequest `thrift:"req,1" frugal:"1,default,SubmitAnswerRequest" json:"req"`
}

func NewInterviewServiceSubmitAnswerArgs() *InterviewServiceSubmitAnswerArgs {
	return &InterviewServiceSubmitAnswerArgs{}
}

func (p *InterviewServiceSubmitAnswerArgs) InitDefault() {
}

var InterviewServiceSubmitAnswerArgs_Req_DEFAULT *SubmitAnswerRequest

func (p *InterviewServiceSubmitAnswerArgs) GetReq() (v *SubmitAnswerRequest) {
	if !p.IsSetReq() {
		return InterviewServiceSubmitAnswerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceSubmitAnswerArgs) SetReq(val *SubmitAnswerRequest) {
	p.Req = val
}

func (p *InterviewServiceSubmitAnswerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceSubmitAnswerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceSubmitAnswerArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceSubmitAnswerArgs = map[int16]string{
	1: "req",
}

type InterviewServiceSubmitAnswerResult struct {
	Success *SubmitAnswerResponse `thrift:"success,0,optional" frugal:"0,optional,SubmitAnswerResponse" json:"success,omitempty"`
}

func NewInterviewServiceSubmitAnswerResult() *InterviewServiceSubmitAnswerResult {
	return &InterviewServiceSubmitAnswerResult{}
}

func (p *InterviewServiceSubmitAnswerResult) InitDefault() {
}

var InterviewServiceSubmitAnswerResult_Success_DEFAULT *SubmitAnswerResponse

func (p *InterviewServiceSubmitAnswerResult) GetSuccess() (v *SubmitAnswerResponse) {
	if !p.IsSetSuccess() {
		return InterviewServiceSubmitAnswerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceSubmitAnswerResult) SetSuccess(x interface{}) {
	p.Success = x.(*SubmitAnswerResponse)
}

func (p *InterviewServiceSubmitAnswerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceSubmitAnswerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceSubmitAnswerResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceSubmitAnswerResult = map[int16]string{
	0: "success",
}

type InterviewServiceFinishInterviewArgs struct {
	Req *FinishInterviewRequest `thrift:"req,1" frugal:"1,default,FinishInterviewRequest" json:"req"`
}

func NewInterviewServiceFinishInterviewArgs() *InterviewServiceFinishInterviewArgs {
	return &InterviewServiceFinishInterviewArgs{}
}

func (p *InterviewServiceFinishInterviewArgs) InitDefault() {
}

var InterviewServiceFinishInterviewArgs_Req_DEFAULT *FinishInterviewRequest

func (p *InterviewServiceFinishInterviewArgs) GetReq() (v *FinishInterviewRequest) {
	if !p.IsSetReq() {
		return InterviewServiceFinishInterviewArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceFinishInterviewArgs) SetReq(val *FinishInterviewRequest) {
	p.Req = val
}

func (p *InterviewServiceFinishInterviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceFinishInterviewArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceFinishInterviewArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceFinishInterviewArgs = map[int16]string{
	1: "req",
}

type InterviewServiceFinishInterviewResult struct {
	Success *FinishInterviewResponse `thrift:"success,0,optional" frugal:"0,optional,FinishInterviewResponse" json:"success,omitempty"`
}

func NewInterviewServiceFinishInterviewResult() *InterviewServiceFinishInterviewResult {
	return &InterviewServiceFinishInterviewResult{}
}

func (p *InterviewServiceFinishInterviewResult) InitDefault() {
}

var InterviewServiceFinishInterviewResult_Success_DEFAULT *FinishInterviewResponse

func (p *InterviewServiceFinishInterviewResult) GetSuccess() (v *FinishInterviewResponse) {
	if !p.IsSetSuccess() {
		return InterviewServiceFinishInterviewResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceFinishInterviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*FinishInterviewResponse)
}

func (p *InterviewServiceFinishInterviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceFinishInterviewResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceFinishInterviewResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceFinishInterviewResult = map[int16]string{
	0: "success",
}

type InterviewServiceGetInterviewDetailArgs struct {
	Req *GetInterviewDetailRequest `thrift:"req,1" frugal:"1,default,GetInterviewDetailRequest" json:"req"`
}

func NewInterviewServiceGetInterviewDetailArgs() *InterviewServiceGetInterviewDetailArgs {
	return &InterviewServiceGetInterviewDetailArgs{}
}

func (p *InterviewServiceGetInterviewDetailArgs) InitDefault() {
}

var InterviewServiceGetInterviewDetailArgs_Req_DEFAULT *GetInterviewDetailRequest

func (p *InterviewServiceGetInterviewDetailArgs) GetReq() (v *GetInterviewDetailRequest) {
	if !p.IsSetReq() {
		return InterviewServiceGetInterviewDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceGetInterviewDetailArgs) SetReq(val *GetInterviewDetailRequest) {
	p.Req = val
}

func (p *InterviewServiceGetInterviewDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceGetInterviewDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetInterviewDetailArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetInterviewDetailArgs = map[int16]string{
	1: "req",
}

type InterviewServiceGetInterviewDetailResult struct {
	Success *GetInterviewDetailResponse `thrift:"success,0,optional" frugal:"0,optional,GetInterviewDetailResponse" json:"success,omitempty"`
}

func NewInterviewServiceGetInterviewDetailResult() *InterviewServiceGetInterviewDetailResult {
	return &InterviewServiceGetInterviewDetailResult{}
}

func (p *InterviewServiceGetInterviewDetailResult) InitDefault() {
}

var InterviewServiceGetInterviewDetailResult_Success_DEFAULT *GetInterviewDetailResponse

func (p *InterviewServiceGetInterviewDetailResult) GetSuccess() (v *GetInterviewDetailResponse) {
	if !p.IsSetSuccess() {
		return InterviewServiceGetInterviewDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceGetInterviewDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetInterviewDetailResponse)
}

func (p *InterviewServiceGetInterviewDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceGetInterviewDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetInterviewDetailResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetInterviewDetailResult = map[int16]string{
	0: "success",
}

type InterviewServiceGetInterviewHistoryArgs struct {
	Req *GetInterviewHistoryRequest `thrift:"req,1" frugal:"1,default,GetInterviewHistoryRequest" json:"req"`
}

func NewInterviewServiceGetInterviewHistoryArgs() *InterviewServiceGetInterviewHistoryArgs {
	return &InterviewServiceGetInterviewHistoryArgs{}
}

func (p *InterviewServiceGetInterviewHistoryArgs) InitDefault() {
}

var InterviewServiceGetInterviewHistoryArgs_Req_DEFAULT *GetInterviewHistoryRequest

func (p *InterviewServiceGetInterviewHistoryArgs) GetReq() (v *GetInterviewHistoryRequest) {
	if !p.IsSetReq() {
		return InterviewServiceGetInterviewHistoryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceGetInterviewHistoryArgs) SetReq(val *GetInterviewHistoryRequest) {
	p.Req = val
}

func (p *InterviewServiceGetInterviewHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceGetInterviewHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetInterviewHistoryArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetInterviewHistoryArgs = map[int16]string{
	1: "req",
}

type InterviewServiceGetInterviewHistoryResult struct {
	Success *GetInterviewHistoryResponse `thrift:"success,0,optional" frugal:"0,optional,GetInterviewHistoryResponse" json:"success,omitempty"`
}

func NewInterviewServiceGetInterviewHistoryResult() *InterviewServiceGetInterviewHistoryResult {
	return &InterviewServiceGetInterviewHistoryResult{}
}

func (p *InterviewServiceGetInterviewHistoryResult) InitDefault() {
}

var InterviewServiceGetInterviewHistoryResult_Success_DEFAULT *GetInterviewHistoryResponse

func (p *InterviewServiceGetInterviewHistoryResult) GetSuccess() (v *GetInterviewHistoryResponse) {
	if !p.IsSetSuccess() {
		return InterviewServiceGetInterviewHistoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceGetInterviewHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetInterviewHistoryResponse)
}

func (p *InterviewServiceGetInterviewHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceGetInterviewHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetInterviewHistoryResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetInterviewHistoryResult = map[int16]string{
	0: "success",
}

type InterviewServiceAnalyzeResumeArgs struct {
	Req *AnalyzeResumeRequest `thrift:"req,1" frugal:"1,default,AnalyzeResumeRequest" json:"req"`
}

func NewInterviewServiceAnalyzeResumeArgs() *InterviewServiceAnalyzeResumeArgs {
	return &InterviewServiceAnalyzeResumeArgs{}
}

func (p *InterviewServiceAnalyzeResumeArgs) InitDefault() {
}

var InterviewServiceAnalyzeResumeArgs_Req_DEFAULT *AnalyzeResumeRequest

func (p *InterviewServiceAnalyzeResumeArgs) GetReq() (v *AnalyzeResumeRequest) {
	if !p.IsSetReq() {
		return InterviewServiceAnalyzeResumeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceAnalyzeResumeArgs) SetReq(val *AnalyzeResumeRequest) {
	p.Req = val
}

func (p *InterviewServiceAnalyzeResumeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceAnalyzeResumeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceAnalyzeResumeArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceAnalyzeResumeArgs = map[int16]string{
	1: "req",
}

type InterviewServiceAnalyzeResumeResult struct {
	Success *AnalyzeResumeResponse `thrift:"success,0,optional" frugal:"0,optional,AnalyzeResumeResponse" json:"success,omitempty"`
}

func NewInterviewServiceAnalyzeResumeResult() *InterviewServiceAnalyzeResumeResult {
	return &InterviewServiceAnalyzeResumeResult{}
}

func (p *InterviewServiceAnalyzeResumeResult) InitDefault() {
}

var InterviewServiceAnalyzeResumeResult_Success_DEFAULT *AnalyzeResumeResponse

func (p *InterviewServiceAnalyzeResumeResult) GetSuccess() (v *AnalyzeResumeResponse) {
	if !p.IsSetSuccess() {
		return InterviewServiceAnalyzeResumeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceAnalyzeResumeResult) SetSuccess(x interface{}) {
	p.Success = x.(*AnalyzeResumeResponse)
}

func (p *InterviewServiceAnalyzeResumeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceAnalyzeResumeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceAnalyzeResumeResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceAnalyzeResumeResult = map[int16]string{
	0: "success",
}

type InterviewServiceGetAbilityAnalysisArgs struct {
	Req *GetAbilityAnalysisRequest `thrift:"req,1" frugal:"1,default,GetAbilityAnalysisRequest" json:"req"`
}

func NewInterviewServiceGetAbilityAnalysisArgs() *InterviewServiceGetAbilityAnalysisArgs {
	return &InterviewServiceGetAbilityAnalysisArgs{}
}

func (p *InterviewServiceGetAbilityAnalysisArgs) InitDefault() {
}

var InterviewServiceGetAbilityAnalysisArgs_Req_DEFAULT *GetAbilityAnalysisRequest

func (p *InterviewServiceGetAbilityAnalysisArgs) GetReq() (v *GetAbilityAnalysisRequest) {
	if !p.IsSetReq() {
		return InterviewServiceGetAbilityAnalysisArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceGetAbilityAnalysisArgs) SetReq(val *GetAbilityAnalysisRequest) {
	p.Req = val
}

func (p *InterviewServiceGetAbilityAnalysisArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceGetAbilityAnalysisArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetAbilityAnalysisArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetAbilityAnalysisArgs = map[int16]string{
	1: "req",
}

type InterviewServiceGetAbilityAnalysisResult struct {
	Success *GetAbilityAnalysisResponse `thrift:"success,0,optional" frugal:"0,optional,GetAbilityAnalysisResponse" json:"success,omitempty"`
}

func NewInterviewServiceGetAbilityAnalysisResult() *InterviewServiceGetAbilityAnalysisResult {
	return &InterviewServiceGetAbilityAnalysisResult{}
}

func (p *InterviewServiceGetAbilityAnalysisResult) InitDefault() {
}

var InterviewServiceGetAbilityAnalysisResult_Success_DEFAULT *GetAbilityAnalysisResponse

func (p *InterviewServiceGetAbilityAnalysisResult) GetSuccess() (v *GetAbilityAnalysisResponse) {
	if !p.IsSetSuccess() {
		return InterviewServiceGetAbilityAnalysisResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceGetAbilityAnalysisResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAbilityAnalysisResponse)
}

func (p *InterviewServiceGetAbilityAnalysisResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceGetAbilityAnalysisResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetAbilityAnalysisResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetAbilityAnalysisResult = map[int16]string{
	0: "success",
}
