// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package storage

import (
	"context"
	"fmt"
	"zpi/server/shared/kitex_gen/base"
)

type GetUploadUrlRequest struct {
	UserId      int64         `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileName    string        `thrift:"file_name,2" frugal:"2,default,string" json:"file_name"`
	FileType    base.FileType `thrift:"file_type,3" frugal:"3,default,FileType" json:"file_type"`
	ContentType string        `thrift:"content_type,4" frugal:"4,default,string" json:"content_type"`
}

func NewGetUploadUrlRequest() *GetUploadUrlRequest {
	return &GetUploadUrlRequest{}
}

func (p *GetUploadUrlRequest) InitDefault() {
}

func (p *GetUploadUrlRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetUploadUrlRequest) GetFileName() (v string) {
	return p.FileName
}

func (p *GetUploadUrlRequest) GetFileType() (v base.FileType) {
	return p.FileType
}

func (p *GetUploadUrlRequest) GetContentType() (v string) {
	return p.ContentType
}
func (p *GetUploadUrlRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetUploadUrlRequest) SetFileName(val string) {
	p.FileName = val
}
func (p *GetUploadUrlRequest) SetFileType(val base.FileType) {
	p.FileType = val
}
func (p *GetUploadUrlRequest) SetContentType(val string) {
	p.ContentType = val
}

func (p *GetUploadUrlRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUploadUrlRequest(%+v)", *p)
}

var fieldIDToName_GetUploadUrlRequest = map[int16]string{
	1: "user_id",
	2: "file_name",
	3: "file_type",
	4: "content_type",
}

type GetUploadUrlResponse struct {
	BaseResp  *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	UploadUrl string             `thrift:"upload_url,2" frugal:"2,default,string" json:"upload_url"`
	FileKey   string             `thrift:"file_key,3" frugal:"3,default,string" json:"file_key"`
	ExpiresAt int64              `thrift:"expires_at,4" frugal:"4,default,i64" json:"expires_at"`
}

func NewGetUploadUrlResponse() *GetUploadUrlResponse {
	return &GetUploadUrlResponse{}
}

func (p *GetUploadUrlResponse) InitDefault() {
}

var GetUploadUrlResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetUploadUrlResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetUploadUrlResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetUploadUrlResponse) GetUploadUrl() (v string) {
	return p.UploadUrl
}

func (p *GetUploadUrlResponse) GetFileKey() (v string) {
	return p.FileKey
}

func (p *GetUploadUrlResponse) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}
func (p *GetUploadUrlResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetUploadUrlResponse) SetUploadUrl(val string) {
	p.UploadUrl = val
}
func (p *GetUploadUrlResponse) SetFileKey(val string) {
	p.FileKey = val
}
func (p *GetUploadUrlResponse) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}

func (p *GetUploadUrlResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUploadUrlResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUploadUrlResponse(%+v)", *p)
}

var fieldIDToName_GetUploadUrlResponse = map[int16]string{
	1: "base_resp",
	2: "upload_url",
	3: "file_key",
	4: "expires_at",
}

type ConfirmUploadRequest struct {
	UserId   int64         `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileKey  string        `thrift:"file_key,2" frugal:"2,default,string" json:"file_key"`
	FileType base.FileType `thrift:"file_type,3" frugal:"3,default,FileType" json:"file_type"`
}

func NewConfirmUploadRequest() *ConfirmUploadRequest {
	return &ConfirmUploadRequest{}
}

func (p *ConfirmUploadRequest) InitDefault() {
}

func (p *ConfirmUploadRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ConfirmUploadRequest) GetFileKey() (v string) {
	return p.FileKey
}

func (p *ConfirmUploadRequest) GetFileType() (v base.FileType) {
	return p.FileType
}
func (p *ConfirmUploadRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ConfirmUploadRequest) SetFileKey(val string) {
	p.FileKey = val
}
func (p *ConfirmUploadRequest) SetFileType(val base.FileType) {
	p.FileType = val
}

func (p *ConfirmUploadRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmUploadRequest(%+v)", *p)
}

var fieldIDToName_ConfirmUploadRequest = map[int16]string{
	1: "user_id",
	2: "file_key",
	3: "file_type",
}

type ConfirmUploadResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	FileUrl  string             `thrift:"file_url,2" frugal:"2,default,string" json:"file_url"`
}

func NewConfirmUploadResponse() *ConfirmUploadResponse {
	return &ConfirmUploadResponse{}
}

func (p *ConfirmUploadResponse) InitDefault() {
}

var ConfirmUploadResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *ConfirmUploadResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return ConfirmUploadResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ConfirmUploadResponse) GetFileUrl() (v string) {
	return p.FileUrl
}
func (p *ConfirmUploadResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *ConfirmUploadResponse) SetFileUrl(val string) {
	p.FileUrl = val
}

func (p *ConfirmUploadResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ConfirmUploadResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmUploadResponse(%+v)", *p)
}

var fieldIDToName_ConfirmUploadResponse = map[int16]string{
	1: "base_resp",
	2: "file_url",
}

type GetDownloadUrlRequest struct {
	UserId  int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileKey string `thrift:"file_key,2" frugal:"2,default,string" json:"file_key"`
}

func NewGetDownloadUrlRequest() *GetDownloadUrlRequest {
	return &GetDownloadUrlRequest{}
}

func (p *GetDownloadUrlRequest) InitDefault() {
}

func (p *GetDownloadUrlRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetDownloadUrlRequest) GetFileKey() (v string) {
	return p.FileKey
}
func (p *GetDownloadUrlRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetDownloadUrlRequest) SetFileKey(val string) {
	p.FileKey = val
}

func (p *GetDownloadUrlRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDownloadUrlRequest(%+v)", *p)
}

var fieldIDToName_GetDownloadUrlRequest = map[int16]string{
	1: "user_id",
	2: "file_key",
}

type GetDownloadUrlResponse struct {
	BaseResp    *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	DownloadUrl string             `thrift:"download_url,2" frugal:"2,default,string" json:"download_url"`
	ExpiresAt   int64              `thrift:"expires_at,3" frugal:"3,default,i64" json:"expires_at"`
}

func NewGetDownloadUrlResponse() *GetDownloadUrlResponse {
	return &GetDownloadUrlResponse{}
}

func (p *GetDownloadUrlResponse) InitDefault() {
}

var GetDownloadUrlResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetDownloadUrlResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetDownloadUrlResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetDownloadUrlResponse) GetDownloadUrl() (v string) {
	return p.DownloadUrl
}

func (p *GetDownloadUrlResponse) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}
func (p *GetDownloadUrlResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetDownloadUrlResponse) SetDownloadUrl(val string) {
	p.DownloadUrl = val
}
func (p *GetDownloadUrlResponse) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}

func (p *GetDownloadUrlResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetDownloadUrlResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDownloadUrlResponse(%+v)", *p)
}

var fieldIDToName_GetDownloadUrlResponse = map[int16]string{
	1: "base_resp",
	2: "download_url",
	3: "expires_at",
}

type DeleteFileRequest struct {
	UserId  int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileKey string `thrift:"file_key,2" frugal:"2,default,string" json:"file_key"`
}

func NewDeleteFileRequest() *DeleteFileRequest {
	return &DeleteFileRequest{}
}

func (p *DeleteFileRequest) InitDefault() {
}

func (p *DeleteFileRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *DeleteFileRequest) GetFileKey() (v string) {
	return p.FileKey
}
func (p *DeleteFileRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *DeleteFileRequest) SetFileKey(val string) {
	p.FileKey = val
}

func (p *DeleteFileRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFileRequest(%+v)", *p)
}

var fieldIDToName_DeleteFileRequest = map[int16]string{
	1: "user_id",
	2: "file_key",
}

type DeleteFileResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
}

func NewDeleteFileResponse() *DeleteFileResponse {
	return &DeleteFileResponse{}
}

func (p *DeleteFileResponse) InitDefault() {
}

var DeleteFileResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *DeleteFileResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return DeleteFileResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteFileResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}

func (p *DeleteFileResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteFileResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteFileResponse(%+v)", *p)
}

var fieldIDToName_DeleteFileResponse = map[int16]string{
	1: "base_resp",
}

type GetFileInfoRequest struct {
	FileKey string `thrift:"file_key,1" frugal:"1,default,string" json:"file_key"`
}

func NewGetFileInfoRequest() *GetFileInfoRequest {
	return &GetFileInfoRequest{}
}

func (p *GetFileInfoRequest) InitDefault() {
}

func (p *GetFileInfoRequest) GetFileKey() (v string) {
	return p.FileKey
}
func (p *GetFileInfoRequest) SetFileKey(val string) {
	p.FileKey = val
}

func (p *GetFileInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFileInfoRequest(%+v)", *p)
}

var fieldIDToName_GetFileInfoRequest = map[int16]string{
	1: "file_key",
}

type GetFileInfoResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	FileInfo *base.FileInfo     `thrift:"file_info,2" frugal:"2,default,base.FileInfo" json:"file_info"`
}

func NewGetFileInfoResponse() *GetFileInfoResponse {
	return &GetFileInfoResponse{}
}

func (p *GetFileInfoResponse) InitDefault() {
}

var GetFileInfoResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetFileInfoResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetFileInfoResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetFileInfoResponse_FileInfo_DEFAULT *base.FileInfo

func (p *GetFileInfoResponse) GetFileInfo() (v *base.FileInfo) {
	if !p.IsSetFileInfo() {
		return GetFileInfoResponse_FileInfo_DEFAULT
	}
	return p.FileInfo
}
func (p *GetFileInfoResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetFileInfoResponse) SetFileInfo(val *base.FileInfo) {
	p.FileInfo = val
}

func (p *GetFileInfoResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetFileInfoResponse) IsSetFileInfo() bool {
	return p.FileInfo != nil
}

func (p *GetFileInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFileInfoResponse(%+v)", *p)
}

var fieldIDToName_GetFileInfoResponse = map[int16]string{
	1: "base_resp",
	2: "file_info",
}

type BatchDeleteFilesRequest struct {
	UserId   int64    `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileKeys []string `thrift:"file_keys,2" frugal:"2,default,list<string>" json:"file_keys"`
}

func NewBatchDeleteFilesRequest() *BatchDeleteFilesRequest {
	return &BatchDeleteFilesRequest{}
}

func (p *BatchDeleteFilesRequest) InitDefault() {
}

func (p *BatchDeleteFilesRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *BatchDeleteFilesRequest) GetFileKeys() (v []string) {
	return p.FileKeys
}
func (p *BatchDeleteFilesRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *BatchDeleteFilesRequest) SetFileKeys(val []string) {
	p.FileKeys = val
}

func (p *BatchDeleteFilesRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchDeleteFilesRequest(%+v)", *p)
}

var fieldIDToName_BatchDeleteFilesRequest = map[int16]string{
	1: "user_id",
	2: "file_keys",
}

type BatchDeleteFilesResponse struct {
	BaseResp     *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	DeletedCount int32              `thrift:"deleted_count,2" frugal:"2,default,i32" json:"deleted_count"`
}

func NewBatchDeleteFilesResponse() *BatchDeleteFilesResponse {
	return &BatchDeleteFilesResponse{}
}

func (p *BatchDeleteFilesResponse) InitDefault() {
}

var BatchDeleteFilesResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *BatchDeleteFilesResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return BatchDeleteFilesResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *BatchDeleteFilesResponse) GetDeletedCount() (v int32) {
	return p.DeletedCount
}
func (p *BatchDeleteFilesResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *BatchDeleteFilesResponse) SetDeletedCount(val int32) {
	p.DeletedCount = val
}

func (p *BatchDeleteFilesResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *BatchDeleteFilesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchDeleteFilesResponse(%+v)", *p)
}

var fieldIDToName_BatchDeleteFilesResponse = map[int16]string{
	1: "base_resp",
	2: "deleted_count",
}

type GetUserFilesRequest struct {
	UserId   int64             `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	FileType *base.FileType    `thrift:"file_type,2,optional" frugal:"2,optional,FileType" json:"file_type,omitempty"`
	Page     *base.PageRequest `thrift:"page,3" frugal:"3,default,base.PageRequest" json:"page"`
}

func NewGetUserFilesRequest() *GetUserFilesRequest {
	return &GetUserFilesRequest{}
}

func (p *GetUserFilesRequest) InitDefault() {
}

func (p *GetUserFilesRequest) GetUserId() (v int64) {
	return p.UserId
}

var GetUserFilesRequest_FileType_DEFAULT base.FileType

func (p *GetUserFilesRequest) GetFileType() (v base.FileType) {
	if !p.IsSetFileType() {
		return GetUserFilesRequest_FileType_DEFAULT
	}
	return *p.FileType
}

var GetUserFilesRequest_Page_DEFAULT *base.PageRequest

func (p *GetUserFilesRequest) GetPage() (v *base.PageRequest) {
	if !p.IsSetPage() {
		return GetUserFilesRequest_Page_DEFAULT
	}
	return p.Page
}
func (p *GetUserFilesRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetUserFilesRequest) SetFileType(val *base.FileType) {
	p.FileType = val
}
func (p *GetUserFilesRequest) SetPage(val *base.PageRequest) {
	p.Page = val
}

func (p *GetUserFilesRequest) IsSetFileType() bool {
	return p.FileType != nil
}

func (p *GetUserFilesRequest) IsSetPage() bool {
	return p.Page != nil
}

func (p *GetUserFilesRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserFilesRequest(%+v)", *p)
}

var fieldIDToName_GetUserFilesRequest = map[int16]string{
	1: "user_id",
	2: "file_type",
	3: "page",
}

type GetUserFilesResponse struct {
	BaseResp *base.BaseResponse `thrift:"base_resp,1" frugal:"1,default,base.BaseResponse" json:"base_resp"`
	Files    []*base.FileInfo   `thrift:"files,2" frugal:"2,default,list<base.FileInfo>" json:"files"`
	Page     *base.PageResponse `thrift:"page,3" frugal:"3,default,base.PageResponse" json:"page"`
}

func NewGetUserFilesResponse() *GetUserFilesResponse {
	return &GetUserFilesResponse{}
}

func (p *GetUserFilesResponse) InitDefault() {
}

var GetUserFilesResponse_BaseResp_DEFAULT *base.BaseResponse

func (p *GetUserFilesResponse) GetBaseResp() (v *base.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetUserFilesResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetUserFilesResponse) GetFiles() (v []*base.FileInfo) {
	return p.Files
}

var GetUserFilesResponse_Page_DEFAULT *base.PageResponse

func (p *GetUserFilesResponse) GetPage() (v *base.PageResponse) {
	if !p.IsSetPage() {
		return GetUserFilesResponse_Page_DEFAULT
	}
	return p.Page
}
func (p *GetUserFilesResponse) SetBaseResp(val *base.BaseResponse) {
	p.BaseResp = val
}
func (p *GetUserFilesResponse) SetFiles(val []*base.FileInfo) {
	p.Files = val
}
func (p *GetUserFilesResponse) SetPage(val *base.PageResponse) {
	p.Page = val
}

func (p *GetUserFilesResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserFilesResponse) IsSetPage() bool {
	return p.Page != nil
}

func (p *GetUserFilesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserFilesResponse(%+v)", *p)
}

var fieldIDToName_GetUserFilesResponse = map[int16]string{
	1: "base_resp",
	2: "files",
	3: "page",
}

type StorageService interface {
	HealthCheck(ctx context.Context) (r *base.HealthCheckResponse, err error)

	GetUploadUrl(ctx context.Context, req *GetUploadUrlRequest) (r *GetUploadUrlResponse, err error)

	ConfirmUpload(ctx context.Context, req *ConfirmUploadRequest) (r *ConfirmUploadResponse, err error)

	GetDownloadUrl(ctx context.Context, req *GetDownloadUrlRequest) (r *GetDownloadUrlResponse, err error)

	GetFileInfo(ctx context.Context, req *GetFileInfoRequest) (r *GetFileInfoResponse, err error)

	GetUserFiles(ctx context.Context, req *GetUserFilesRequest) (r *GetUserFilesResponse, err error)

	DeleteFile(ctx context.Context, req *DeleteFileRequest) (r *DeleteFileResponse, err error)

	BatchDeleteFiles(ctx context.Context, req *BatchDeleteFilesRequest) (r *BatchDeleteFilesResponse, err error)
}

type StorageServiceHealthCheckArgs struct {
}

func NewStorageServiceHealthCheckArgs() *StorageServiceHealthCheckArgs {
	return &StorageServiceHealthCheckArgs{}
}

func (p *StorageServiceHealthCheckArgs) InitDefault() {
}

func (p *StorageServiceHealthCheckArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceHealthCheckArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceHealthCheckArgs = map[int16]string{}

type StorageServiceHealthCheckResult struct {
	Success *base.HealthCheckResponse `thrift:"success,0,optional" frugal:"0,optional,base.HealthCheckResponse" json:"success,omitempty"`
}

func NewStorageServiceHealthCheckResult() *StorageServiceHealthCheckResult {
	return &StorageServiceHealthCheckResult{}
}

func (p *StorageServiceHealthCheckResult) InitDefault() {
}

var StorageServiceHealthCheckResult_Success_DEFAULT *base.HealthCheckResponse

func (p *StorageServiceHealthCheckResult) GetSuccess() (v *base.HealthCheckResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceHealthCheckResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceHealthCheckResult) SetSuccess(x interface{}) {
	p.Success = x.(*base.HealthCheckResponse)
}

func (p *StorageServiceHealthCheckResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceHealthCheckResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceHealthCheckResult(%+v)", *p)
}

var fieldIDToName_StorageServiceHealthCheckResult = map[int16]string{
	0: "success",
}

type StorageServiceGetUploadUrlArgs struct {
	Req *GetUploadUrlRequest `thrift:"req,1" frugal:"1,default,GetUploadUrlRequest" json:"req"`
}

func NewStorageServiceGetUploadUrlArgs() *StorageServiceGetUploadUrlArgs {
	return &StorageServiceGetUploadUrlArgs{}
}

func (p *StorageServiceGetUploadUrlArgs) InitDefault() {
}

var StorageServiceGetUploadUrlArgs_Req_DEFAULT *GetUploadUrlRequest

func (p *StorageServiceGetUploadUrlArgs) GetReq() (v *GetUploadUrlRequest) {
	if !p.IsSetReq() {
		return StorageServiceGetUploadUrlArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StorageServiceGetUploadUrlArgs) SetReq(val *GetUploadUrlRequest) {
	p.Req = val
}

func (p *StorageServiceGetUploadUrlArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StorageServiceGetUploadUrlArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetUploadUrlArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceGetUploadUrlArgs = map[int16]string{
	1: "req",
}

type StorageServiceGetUploadUrlResult struct {
	Success *GetUploadUrlResponse `thrift:"success,0,optional" frugal:"0,optional,GetUploadUrlResponse" json:"success,omitempty"`
}

func NewStorageServiceGetUploadUrlResult() *StorageServiceGetUploadUrlResult {
	return &StorageServiceGetUploadUrlResult{}
}

func (p *StorageServiceGetUploadUrlResult) InitDefault() {
}

var StorageServiceGetUploadUrlResult_Success_DEFAULT *GetUploadUrlResponse

func (p *StorageServiceGetUploadUrlResult) GetSuccess() (v *GetUploadUrlResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceGetUploadUrlResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceGetUploadUrlResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUploadUrlResponse)
}

func (p *StorageServiceGetUploadUrlResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceGetUploadUrlResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetUploadUrlResult(%+v)", *p)
}

var fieldIDToName_StorageServiceGetUploadUrlResult = map[int16]string{
	0: "success",
}

type StorageServiceConfirmUploadArgs struct {
	Req *ConfirmUploadRequest `thrift:"req,1" frugal:"1,default,ConfirmUploadRequest" json:"req"`
}

func NewStorageServiceConfirmUploadArgs() *StorageServiceConfirmUploadArgs {
	return &StorageServiceConfirmUploadArgs{}
}

func (p *StorageServiceConfirmUploadArgs) InitDefault() {
}

var StorageServiceConfirmUploadArgs_Req_DEFAULT *ConfirmUploadRequest

func (p *StorageServiceConfirmUploadArgs) GetReq() (v *ConfirmUploadRequest) {
	if !p.IsSetReq() {
		return StorageServiceConfirmUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StorageServiceConfirmUploadArgs) SetReq(val *ConfirmUploadRequest) {
	p.Req = val
}

func (p *StorageServiceConfirmUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StorageServiceConfirmUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceConfirmUploadArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceConfirmUploadArgs = map[int16]string{
	1: "req",
}

type StorageServiceConfirmUploadResult struct {
	Success *ConfirmUploadResponse `thrift:"success,0,optional" frugal:"0,optional,ConfirmUploadResponse" json:"success,omitempty"`
}

func NewStorageServiceConfirmUploadResult() *StorageServiceConfirmUploadResult {
	return &StorageServiceConfirmUploadResult{}
}

func (p *StorageServiceConfirmUploadResult) InitDefault() {
}

var StorageServiceConfirmUploadResult_Success_DEFAULT *ConfirmUploadResponse

func (p *StorageServiceConfirmUploadResult) GetSuccess() (v *ConfirmUploadResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceConfirmUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceConfirmUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*ConfirmUploadResponse)
}

func (p *StorageServiceConfirmUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceConfirmUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceConfirmUploadResult(%+v)", *p)
}

var fieldIDToName_StorageServiceConfirmUploadResult = map[int16]string{
	0: "success",
}

type StorageServiceGetDownloadUrlArgs struct {
	Req *GetDownloadUrlRequest `thrift:"req,1" frugal:"1,default,GetDownloadUrlRequest" json:"req"`
}

func NewStorageServiceGetDownloadUrlArgs() *StorageServiceGetDownloadUrlArgs {
	return &StorageServiceGetDownloadUrlArgs{}
}

func (p *StorageServiceGetDownloadUrlArgs) InitDefault() {
}

var StorageServiceGetDownloadUrlArgs_Req_DEFAULT *GetDownloadUrlRequest

func (p *StorageServiceGetDownloadUrlArgs) GetReq() (v *GetDownloadUrlRequest) {
	if !p.IsSetReq() {
		return StorageServiceGetDownloadUrlArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StorageServiceGetDownloadUrlArgs) SetReq(val *GetDownloadUrlRequest) {
	p.Req = val
}

func (p *StorageServiceGetDownloadUrlArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StorageServiceGetDownloadUrlArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetDownloadUrlArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceGetDownloadUrlArgs = map[int16]string{
	1: "req",
}

type StorageServiceGetDownloadUrlResult struct {
	Success *GetDownloadUrlResponse `thrift:"success,0,optional" frugal:"0,optional,GetDownloadUrlResponse" json:"success,omitempty"`
}

func NewStorageServiceGetDownloadUrlResult() *StorageServiceGetDownloadUrlResult {
	return &StorageServiceGetDownloadUrlResult{}
}

func (p *StorageServiceGetDownloadUrlResult) InitDefault() {
}

var StorageServiceGetDownloadUrlResult_Success_DEFAULT *GetDownloadUrlResponse

func (p *StorageServiceGetDownloadUrlResult) GetSuccess() (v *GetDownloadUrlResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceGetDownloadUrlResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceGetDownloadUrlResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetDownloadUrlResponse)
}

func (p *StorageServiceGetDownloadUrlResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceGetDownloadUrlResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetDownloadUrlResult(%+v)", *p)
}

var fieldIDToName_StorageServiceGetDownloadUrlResult = map[int16]string{
	0: "success",
}

type StorageServiceGetFileInfoArgs struct {
	Req *GetFileInfoRequest `thrift:"req,1" frugal:"1,default,GetFileInfoRequest" json:"req"`
}

func NewStorageServiceGetFileInfoArgs() *StorageServiceGetFileInfoArgs {
	return &StorageServiceGetFileInfoArgs{}
}

func (p *StorageServiceGetFileInfoArgs) InitDefault() {
}

var StorageServiceGetFileInfoArgs_Req_DEFAULT *GetFileInfoRequest

func (p *StorageServiceGetFileInfoArgs) GetReq() (v *GetFileInfoRequest) {
	if !p.IsSetReq() {
		return StorageServiceGetFileInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StorageServiceGetFileInfoArgs) SetReq(val *GetFileInfoRequest) {
	p.Req = val
}

func (p *StorageServiceGetFileInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StorageServiceGetFileInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetFileInfoArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceGetFileInfoArgs = map[int16]string{
	1: "req",
}

type StorageServiceGetFileInfoResult struct {
	Success *GetFileInfoResponse `thrift:"success,0,optional" frugal:"0,optional,GetFileInfoResponse" json:"success,omitempty"`
}

func NewStorageServiceGetFileInfoResult() *StorageServiceGetFileInfoResult {
	return &StorageServiceGetFileInfoResult{}
}

func (p *StorageServiceGetFileInfoResult) InitDefault() {
}

var StorageServiceGetFileInfoResult_Success_DEFAULT *GetFileInfoResponse

func (p *StorageServiceGetFileInfoResult) GetSuccess() (v *GetFileInfoResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceGetFileInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceGetFileInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFileInfoResponse)
}

func (p *StorageServiceGetFileInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceGetFileInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetFileInfoResult(%+v)", *p)
}

var fieldIDToName_StorageServiceGetFileInfoResult = map[int16]string{
	0: "success",
}

type StorageServiceGetUserFilesArgs struct {
	Req *GetUserFilesRequest `thrift:"req,1" frugal:"1,default,GetUserFilesRequest" json:"req"`
}

func NewStorageServiceGetUserFilesArgs() *StorageServiceGetUserFilesArgs {
	return &StorageServiceGetUserFilesArgs{}
}

func (p *StorageServiceGetUserFilesArgs) InitDefault() {
}

var StorageServiceGetUserFilesArgs_Req_DEFAULT *GetUserFilesRequest

func (p *StorageServiceGetUserFilesArgs) GetReq() (v *GetUserFilesRequest) {
	if !p.IsSetReq() {
		return StorageServiceGetUserFilesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StorageServiceGetUserFilesArgs) SetReq(val *GetUserFilesRequest) {
	p.Req = val
}

func (p *StorageServiceGetUserFilesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StorageServiceGetUserFilesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetUserFilesArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceGetUserFilesArgs = map[int16]string{
	1: "req",
}

type StorageServiceGetUserFilesResult struct {
	Success *GetUserFilesResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserFilesResponse" json:"success,omitempty"`
}

func NewStorageServiceGetUserFilesResult() *StorageServiceGetUserFilesResult {
	return &StorageServiceGetUserFilesResult{}
}

func (p *StorageServiceGetUserFilesResult) InitDefault() {
}

var StorageServiceGetUserFilesResult_Success_DEFAULT *GetUserFilesResponse

func (p *StorageServiceGetUserFilesResult) GetSuccess() (v *GetUserFilesResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceGetUserFilesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceGetUserFilesResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserFilesResponse)
}

func (p *StorageServiceGetUserFilesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceGetUserFilesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceGetUserFilesResult(%+v)", *p)
}

var fieldIDToName_StorageServiceGetUserFilesResult = map[int16]string{
	0: "success",
}

type StorageServiceDeleteFileArgs struct {
	Req *DeleteFileRequest `thrift:"req,1" frugal:"1,default,DeleteFileRequest" json:"req"`
}

func NewStorageServiceDeleteFileArgs() *StorageServiceDeleteFileArgs {
	return &StorageServiceDeleteFileArgs{}
}

func (p *StorageServiceDeleteFileArgs) InitDefault() {
}

var StorageServiceDeleteFileArgs_Req_DEFAULT *DeleteFileRequest

func (p *StorageServiceDeleteFileArgs) GetReq() (v *DeleteFileRequest) {
	if !p.IsSetReq() {
		return StorageServiceDeleteFileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StorageServiceDeleteFileArgs) SetReq(val *DeleteFileRequest) {
	p.Req = val
}

func (p *StorageServiceDeleteFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StorageServiceDeleteFileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceDeleteFileArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceDeleteFileArgs = map[int16]string{
	1: "req",
}

type StorageServiceDeleteFileResult struct {
	Success *DeleteFileResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteFileResponse" json:"success,omitempty"`
}

func NewStorageServiceDeleteFileResult() *StorageServiceDeleteFileResult {
	return &StorageServiceDeleteFileResult{}
}

func (p *StorageServiceDeleteFileResult) InitDefault() {
}

var StorageServiceDeleteFileResult_Success_DEFAULT *DeleteFileResponse

func (p *StorageServiceDeleteFileResult) GetSuccess() (v *DeleteFileResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceDeleteFileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceDeleteFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteFileResponse)
}

func (p *StorageServiceDeleteFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceDeleteFileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceDeleteFileResult(%+v)", *p)
}

var fieldIDToName_StorageServiceDeleteFileResult = map[int16]string{
	0: "success",
}

type StorageServiceBatchDeleteFilesArgs struct {
	Req *BatchDeleteFilesRequest `thrift:"req,1" frugal:"1,default,BatchDeleteFilesRequest" json:"req"`
}

func NewStorageServiceBatchDeleteFilesArgs() *StorageServiceBatchDeleteFilesArgs {
	return &StorageServiceBatchDeleteFilesArgs{}
}

func (p *StorageServiceBatchDeleteFilesArgs) InitDefault() {
}

var StorageServiceBatchDeleteFilesArgs_Req_DEFAULT *BatchDeleteFilesRequest

func (p *StorageServiceBatchDeleteFilesArgs) GetReq() (v *BatchDeleteFilesRequest) {
	if !p.IsSetReq() {
		return StorageServiceBatchDeleteFilesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *StorageServiceBatchDeleteFilesArgs) SetReq(val *BatchDeleteFilesRequest) {
	p.Req = val
}

func (p *StorageServiceBatchDeleteFilesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StorageServiceBatchDeleteFilesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceBatchDeleteFilesArgs(%+v)", *p)
}

var fieldIDToName_StorageServiceBatchDeleteFilesArgs = map[int16]string{
	1: "req",
}

type StorageServiceBatchDeleteFilesResult struct {
	Success *BatchDeleteFilesResponse `thrift:"success,0,optional" frugal:"0,optional,BatchDeleteFilesResponse" json:"success,omitempty"`
}

func NewStorageServiceBatchDeleteFilesResult() *StorageServiceBatchDeleteFilesResult {
	return &StorageServiceBatchDeleteFilesResult{}
}

func (p *StorageServiceBatchDeleteFilesResult) InitDefault() {
}

var StorageServiceBatchDeleteFilesResult_Success_DEFAULT *BatchDeleteFilesResponse

func (p *StorageServiceBatchDeleteFilesResult) GetSuccess() (v *BatchDeleteFilesResponse) {
	if !p.IsSetSuccess() {
		return StorageServiceBatchDeleteFilesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StorageServiceBatchDeleteFilesResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchDeleteFilesResponse)
}

func (p *StorageServiceBatchDeleteFilesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StorageServiceBatchDeleteFilesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StorageServiceBatchDeleteFilesResult(%+v)", *p)
}

var fieldIDToName_StorageServiceBatchDeleteFilesResult = map[int16]string{
	0: "success",
}
