// Code generated by Kitex v0.15.3. DO NOT EDIT.

package agentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	agent "zpi/server/shared/kitex_gen/agent"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"StartInterview": kitex.NewMethodInfo(
		startInterviewHandler,
		newAgentServiceStartInterviewArgs,
		newAgentServiceStartInterviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SubmitAnswer": kitex.NewMethodInfo(
		submitAnswerHandler,
		newAgentServiceSubmitAnswerArgs,
		newAgentServiceSubmitAnswerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FinishInterview": kitex.NewMethodInfo(
		finishInterviewHandler,
		newAgentServiceFinishInterviewArgs,
		newAgentServiceFinishInterviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetInterviewDetail": kitex.NewMethodInfo(
		getInterviewDetailHandler,
		newAgentServiceGetInterviewDetailArgs,
		newAgentServiceGetInterviewDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetInterviewHistory": kitex.NewMethodInfo(
		getInterviewHistoryHandler,
		newAgentServiceGetInterviewHistoryArgs,
		newAgentServiceGetInterviewHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AnalyzeResume": kitex.NewMethodInfo(
		analyzeResumeHandler,
		newAgentServiceAnalyzeResumeArgs,
		newAgentServiceAnalyzeResumeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAbilityAnalysis": kitex.NewMethodInfo(
		getAbilityAnalysisHandler,
		newAgentServiceGetAbilityAnalysisArgs,
		newAgentServiceGetAbilityAnalysisResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	agentServiceServiceInfo                = NewServiceInfo()
	agentServiceServiceInfoForClient       = NewServiceInfoForClient()
	agentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return agentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AgentService"
	handlerType := (*agent.AgentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "agent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.3",
		Extra:           extra,
	}
	return svcInfo
}

func startInterviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceStartInterviewArgs)
	realResult := result.(*agent.AgentServiceStartInterviewResult)
	success, err := handler.(agent.AgentService).StartInterview(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceStartInterviewArgs() interface{} {
	return agent.NewAgentServiceStartInterviewArgs()
}

func newAgentServiceStartInterviewResult() interface{} {
	return agent.NewAgentServiceStartInterviewResult()
}

func submitAnswerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceSubmitAnswerArgs)
	realResult := result.(*agent.AgentServiceSubmitAnswerResult)
	success, err := handler.(agent.AgentService).SubmitAnswer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceSubmitAnswerArgs() interface{} {
	return agent.NewAgentServiceSubmitAnswerArgs()
}

func newAgentServiceSubmitAnswerResult() interface{} {
	return agent.NewAgentServiceSubmitAnswerResult()
}

func finishInterviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceFinishInterviewArgs)
	realResult := result.(*agent.AgentServiceFinishInterviewResult)
	success, err := handler.(agent.AgentService).FinishInterview(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceFinishInterviewArgs() interface{} {
	return agent.NewAgentServiceFinishInterviewArgs()
}

func newAgentServiceFinishInterviewResult() interface{} {
	return agent.NewAgentServiceFinishInterviewResult()
}

func getInterviewDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceGetInterviewDetailArgs)
	realResult := result.(*agent.AgentServiceGetInterviewDetailResult)
	success, err := handler.(agent.AgentService).GetInterviewDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceGetInterviewDetailArgs() interface{} {
	return agent.NewAgentServiceGetInterviewDetailArgs()
}

func newAgentServiceGetInterviewDetailResult() interface{} {
	return agent.NewAgentServiceGetInterviewDetailResult()
}

func getInterviewHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceGetInterviewHistoryArgs)
	realResult := result.(*agent.AgentServiceGetInterviewHistoryResult)
	success, err := handler.(agent.AgentService).GetInterviewHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceGetInterviewHistoryArgs() interface{} {
	return agent.NewAgentServiceGetInterviewHistoryArgs()
}

func newAgentServiceGetInterviewHistoryResult() interface{} {
	return agent.NewAgentServiceGetInterviewHistoryResult()
}

func analyzeResumeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceAnalyzeResumeArgs)
	realResult := result.(*agent.AgentServiceAnalyzeResumeResult)
	success, err := handler.(agent.AgentService).AnalyzeResume(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceAnalyzeResumeArgs() interface{} {
	return agent.NewAgentServiceAnalyzeResumeArgs()
}

func newAgentServiceAnalyzeResumeResult() interface{} {
	return agent.NewAgentServiceAnalyzeResumeResult()
}

func getAbilityAnalysisHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceGetAbilityAnalysisArgs)
	realResult := result.(*agent.AgentServiceGetAbilityAnalysisResult)
	success, err := handler.(agent.AgentService).GetAbilityAnalysis(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceGetAbilityAnalysisArgs() interface{} {
	return agent.NewAgentServiceGetAbilityAnalysisArgs()
}

func newAgentServiceGetAbilityAnalysisResult() interface{} {
	return agent.NewAgentServiceGetAbilityAnalysisResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) StartInterview(ctx context.Context, req *agent.StartInterviewReq) (r *agent.StartInterviewResp, err error) {
	var _args agent.AgentServiceStartInterviewArgs
	_args.Req = req
	var _result agent.AgentServiceStartInterviewResult
	if err = p.c.Call(ctx, "StartInterview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SubmitAnswer(ctx context.Context, req *agent.SubmitAnswerReq) (r *agent.SubmitAnswerResp, err error) {
	var _args agent.AgentServiceSubmitAnswerArgs
	_args.Req = req
	var _result agent.AgentServiceSubmitAnswerResult
	if err = p.c.Call(ctx, "SubmitAnswer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FinishInterview(ctx context.Context, req *agent.FinishInterviewReq) (r *agent.FinishInterviewResp, err error) {
	var _args agent.AgentServiceFinishInterviewArgs
	_args.Req = req
	var _result agent.AgentServiceFinishInterviewResult
	if err = p.c.Call(ctx, "FinishInterview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetInterviewDetail(ctx context.Context, req *agent.GetInterviewDetailReq) (r *agent.GetInterviewDetailResp, err error) {
	var _args agent.AgentServiceGetInterviewDetailArgs
	_args.Req = req
	var _result agent.AgentServiceGetInterviewDetailResult
	if err = p.c.Call(ctx, "GetInterviewDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetInterviewHistory(ctx context.Context, req *agent.GetInterviewHistoryReq) (r *agent.GetInterviewHistoryResp, err error) {
	var _args agent.AgentServiceGetInterviewHistoryArgs
	_args.Req = req
	var _result agent.AgentServiceGetInterviewHistoryResult
	if err = p.c.Call(ctx, "GetInterviewHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AnalyzeResume(ctx context.Context, req *agent.AnalyzeResumeReq) (r *agent.AnalyzeResumeResp, err error) {
	var _args agent.AgentServiceAnalyzeResumeArgs
	_args.Req = req
	var _result agent.AgentServiceAnalyzeResumeResult
	if err = p.c.Call(ctx, "AnalyzeResume", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAbilityAnalysis(ctx context.Context, req *agent.GetAbilityAnalysisReq) (r *agent.GetAbilityAnalysisResp, err error) {
	var _args agent.AgentServiceGetAbilityAnalysisArgs
	_args.Req = req
	var _result agent.AgentServiceGetAbilityAnalysisResult
	if err = p.c.Call(ctx, "GetAbilityAnalysis", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
