// Code generated by Kitex v0.15.3. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "zpi/server/shared/kitex_gen/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newUserServiceUpdateUserInfoArgs,
		newUserServiceUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangePassword": kitex.NewMethodInfo(
		changePasswordHandler,
		newUserServiceChangePasswordArgs,
		newUserServiceChangePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadResume": kitex.NewMethodInfo(
		uploadResumeHandler,
		newUserServiceUploadResumeArgs,
		newUserServiceUploadResumeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetResume": kitex.NewMethodInfo(
		getResumeHandler,
		newUserServiceGetResumeArgs,
		newUserServiceGetResumeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteResume": kitex.NewMethodInfo(
		deleteResumeHandler,
		newUserServiceDeleteResumeArgs,
		newUserServiceDeleteResumeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.3",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserInfoArgs)
	realResult := result.(*user.UserServiceGetUserInfoResult)
	success, err := handler.(user.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return user.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return user.NewUserServiceGetUserInfoResult()
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateUserInfoArgs)
	realResult := result.(*user.UserServiceUpdateUserInfoResult)
	success, err := handler.(user.UserService).UpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserInfoArgs() interface{} {
	return user.NewUserServiceUpdateUserInfoArgs()
}

func newUserServiceUpdateUserInfoResult() interface{} {
	return user.NewUserServiceUpdateUserInfoResult()
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceChangePasswordArgs)
	realResult := result.(*user.UserServiceChangePasswordResult)
	success, err := handler.(user.UserService).ChangePassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceChangePasswordArgs() interface{} {
	return user.NewUserServiceChangePasswordArgs()
}

func newUserServiceChangePasswordResult() interface{} {
	return user.NewUserServiceChangePasswordResult()
}

func uploadResumeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUploadResumeArgs)
	realResult := result.(*user.UserServiceUploadResumeResult)
	success, err := handler.(user.UserService).UploadResume(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUploadResumeArgs() interface{} {
	return user.NewUserServiceUploadResumeArgs()
}

func newUserServiceUploadResumeResult() interface{} {
	return user.NewUserServiceUploadResumeResult()
}

func getResumeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetResumeArgs)
	realResult := result.(*user.UserServiceGetResumeResult)
	success, err := handler.(user.UserService).GetResume(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetResumeArgs() interface{} {
	return user.NewUserServiceGetResumeArgs()
}

func newUserServiceGetResumeResult() interface{} {
	return user.NewUserServiceGetResumeResult()
}

func deleteResumeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceDeleteResumeArgs)
	realResult := result.(*user.UserServiceDeleteResumeResult)
	success, err := handler.(user.UserService).DeleteResume(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceDeleteResumeArgs() interface{} {
	return user.NewUserServiceDeleteResumeArgs()
}

func newUserServiceDeleteResumeResult() interface{} {
	return user.NewUserServiceDeleteResumeResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.RegisterResp, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.LoginResp, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *user.GetUserInfoReq) (r *user.GetUserInfoResp, err error) {
	var _args user.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result user.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, req *user.UpdateUserInfoReq) (r *user.UpdateUserInfoResp, err error) {
	var _args user.UserServiceUpdateUserInfoArgs
	_args.Req = req
	var _result user.UserServiceUpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, req *user.ChangePasswordReq) (r *user.ChangePasswordResp, err error) {
	var _args user.UserServiceChangePasswordArgs
	_args.Req = req
	var _result user.UserServiceChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadResume(ctx context.Context, req *user.UploadResumeReq) (r *user.UploadResumeResp, err error) {
	var _args user.UserServiceUploadResumeArgs
	_args.Req = req
	var _result user.UserServiceUploadResumeResult
	if err = p.c.Call(ctx, "UploadResume", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetResume(ctx context.Context, req *user.GetResumeReq) (r *user.GetResumeResp, err error) {
	var _args user.UserServiceGetResumeArgs
	_args.Req = req
	var _result user.UserServiceGetResumeResult
	if err = p.c.Call(ctx, "GetResume", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteResume(ctx context.Context, req *user.DeleteResumeReq) (r *user.DeleteResumeResp, err error) {
	var _args user.UserServiceDeleteResumeArgs
	_args.Req = req
	var _result user.UserServiceDeleteResumeResult
	if err = p.c.Call(ctx, "DeleteResume", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
