// Code generated by Kitex v0.15.3. DO NOT EDIT.
package questionservice

import (
	server "github.com/cloudwego/kitex/server"
	question "zpi/server/shared/kitex_gen/question"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler question.QuestionService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler question.QuestionService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
