// Code generated by hertz generator.

package question

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	base "zpi/server/cmd/api/biz/model/base"
	question "zpi/server/cmd/api/biz/model/question"
)

// GetCategories .
// @router /api/v1/question/categories [GET]
func GetCategories(ctx context.Context, c *app.RequestContext) {
	var err error
	var req question.GetCategoriesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(question.GetCategoriesResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetQuestionList .
// @router /api/v1/question/list [GET]
func GetQuestionList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req question.GetQuestionListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(question.GetQuestionListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetQuestionDetail .
// @router /api/v1/question/:question_id [GET]
func GetQuestionDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req int64
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(question.GetQuestionDetailResponse)

	c.JSON(consts.StatusOK, resp)
}

// FavoriteQuestion .
// @router /api/v1/question/favorite [POST]
func FavoriteQuestion(ctx context.Context, c *app.RequestContext) {
	var err error
	var req question.FavoriteQuestionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// UnfavoriteQuestion .
// @router /api/v1/question/favorite/:question_id [DELETE]
func UnfavoriteQuestion(ctx context.Context, c *app.RequestContext) {
	var err error
	var req int64
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFavoriteQuestions .
// @router /api/v1/question/favorites [GET]
func GetFavoriteQuestions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req question.GetFavoriteQuestionsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(question.GetFavoriteQuestionsResponse)

	c.JSON(consts.StatusOK, resp)
}
