// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlfunc

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zpi/server/shared/dal/sqlentity"
)

func newInterviewMessage(db *gorm.DB, opts ...gen.DOOption) interviewMessage {
	_interviewMessage := interviewMessage{}

	_interviewMessage.interviewMessageDo.UseDB(db, opts...)
	_interviewMessage.interviewMessageDo.UseModel(&sqlentity.InterviewMessage{})

	tableName := _interviewMessage.interviewMessageDo.TableName()
	_interviewMessage.ALL = field.NewAsterisk(tableName)
	_interviewMessage.ID = field.NewUint64(tableName, "id")
	_interviewMessage.InterviewID = field.NewUint64(tableName, "interview_id")
	_interviewMessage.Role = field.NewString(tableName, "role")
	_interviewMessage.Content = field.NewString(tableName, "content")
	_interviewMessage.CreatedAt = field.NewTime(tableName, "created_at")

	_interviewMessage.fillFieldMap()

	return _interviewMessage
}

// interviewMessage 面试对话记录表
type interviewMessage struct {
	interviewMessageDo

	ALL         field.Asterisk
	ID          field.Uint64 // 消息ID
	InterviewID field.Uint64 // 面试ID
	Role        field.String // 角色：interviewer-面试官，candidate-候选人
	Content     field.String // 消息内容
	CreatedAt   field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (i interviewMessage) Table(newTableName string) *interviewMessage {
	i.interviewMessageDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i interviewMessage) As(alias string) *interviewMessage {
	i.interviewMessageDo.DO = *(i.interviewMessageDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *interviewMessage) updateTableName(table string) *interviewMessage {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewUint64(table, "id")
	i.InterviewID = field.NewUint64(table, "interview_id")
	i.Role = field.NewString(table, "role")
	i.Content = field.NewString(table, "content")
	i.CreatedAt = field.NewTime(table, "created_at")

	i.fillFieldMap()

	return i
}

func (i *interviewMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *interviewMessage) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["id"] = i.ID
	i.fieldMap["interview_id"] = i.InterviewID
	i.fieldMap["role"] = i.Role
	i.fieldMap["content"] = i.Content
	i.fieldMap["created_at"] = i.CreatedAt
}

func (i interviewMessage) clone(db *gorm.DB) interviewMessage {
	i.interviewMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i interviewMessage) replaceDB(db *gorm.DB) interviewMessage {
	i.interviewMessageDo.ReplaceDB(db)
	return i
}

type interviewMessageDo struct{ gen.DO }

type IInterviewMessageDo interface {
	gen.SubQuery
	Debug() IInterviewMessageDo
	WithContext(ctx context.Context) IInterviewMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInterviewMessageDo
	WriteDB() IInterviewMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInterviewMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInterviewMessageDo
	Not(conds ...gen.Condition) IInterviewMessageDo
	Or(conds ...gen.Condition) IInterviewMessageDo
	Select(conds ...field.Expr) IInterviewMessageDo
	Where(conds ...gen.Condition) IInterviewMessageDo
	Order(conds ...field.Expr) IInterviewMessageDo
	Distinct(cols ...field.Expr) IInterviewMessageDo
	Omit(cols ...field.Expr) IInterviewMessageDo
	Join(table schema.Tabler, on ...field.Expr) IInterviewMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInterviewMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInterviewMessageDo
	Group(cols ...field.Expr) IInterviewMessageDo
	Having(conds ...gen.Condition) IInterviewMessageDo
	Limit(limit int) IInterviewMessageDo
	Offset(offset int) IInterviewMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInterviewMessageDo
	Unscoped() IInterviewMessageDo
	Create(values ...*sqlentity.InterviewMessage) error
	CreateInBatches(values []*sqlentity.InterviewMessage, batchSize int) error
	Save(values ...*sqlentity.InterviewMessage) error
	First() (*sqlentity.InterviewMessage, error)
	Take() (*sqlentity.InterviewMessage, error)
	Last() (*sqlentity.InterviewMessage, error)
	Find() ([]*sqlentity.InterviewMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlentity.InterviewMessage, err error)
	FindInBatches(result *[]*sqlentity.InterviewMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlentity.InterviewMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInterviewMessageDo
	Assign(attrs ...field.AssignExpr) IInterviewMessageDo
	Joins(fields ...field.RelationField) IInterviewMessageDo
	Preload(fields ...field.RelationField) IInterviewMessageDo
	FirstOrInit() (*sqlentity.InterviewMessage, error)
	FirstOrCreate() (*sqlentity.InterviewMessage, error)
	FindByPage(offset int, limit int) (result []*sqlentity.InterviewMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInterviewMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i interviewMessageDo) Debug() IInterviewMessageDo {
	return i.withDO(i.DO.Debug())
}

func (i interviewMessageDo) WithContext(ctx context.Context) IInterviewMessageDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i interviewMessageDo) ReadDB() IInterviewMessageDo {
	return i.Clauses(dbresolver.Read)
}

func (i interviewMessageDo) WriteDB() IInterviewMessageDo {
	return i.Clauses(dbresolver.Write)
}

func (i interviewMessageDo) Session(config *gorm.Session) IInterviewMessageDo {
	return i.withDO(i.DO.Session(config))
}

func (i interviewMessageDo) Clauses(conds ...clause.Expression) IInterviewMessageDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i interviewMessageDo) Returning(value interface{}, columns ...string) IInterviewMessageDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i interviewMessageDo) Not(conds ...gen.Condition) IInterviewMessageDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i interviewMessageDo) Or(conds ...gen.Condition) IInterviewMessageDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i interviewMessageDo) Select(conds ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i interviewMessageDo) Where(conds ...gen.Condition) IInterviewMessageDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i interviewMessageDo) Order(conds ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i interviewMessageDo) Distinct(cols ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i interviewMessageDo) Omit(cols ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i interviewMessageDo) Join(table schema.Tabler, on ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i interviewMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i interviewMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i interviewMessageDo) Group(cols ...field.Expr) IInterviewMessageDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i interviewMessageDo) Having(conds ...gen.Condition) IInterviewMessageDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i interviewMessageDo) Limit(limit int) IInterviewMessageDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i interviewMessageDo) Offset(offset int) IInterviewMessageDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i interviewMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInterviewMessageDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i interviewMessageDo) Unscoped() IInterviewMessageDo {
	return i.withDO(i.DO.Unscoped())
}

func (i interviewMessageDo) Create(values ...*sqlentity.InterviewMessage) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i interviewMessageDo) CreateInBatches(values []*sqlentity.InterviewMessage, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i interviewMessageDo) Save(values ...*sqlentity.InterviewMessage) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i interviewMessageDo) First() (*sqlentity.InterviewMessage, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.InterviewMessage), nil
	}
}

func (i interviewMessageDo) Take() (*sqlentity.InterviewMessage, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.InterviewMessage), nil
	}
}

func (i interviewMessageDo) Last() (*sqlentity.InterviewMessage, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.InterviewMessage), nil
	}
}

func (i interviewMessageDo) Find() ([]*sqlentity.InterviewMessage, error) {
	result, err := i.DO.Find()
	return result.([]*sqlentity.InterviewMessage), err
}

func (i interviewMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlentity.InterviewMessage, err error) {
	buf := make([]*sqlentity.InterviewMessage, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i interviewMessageDo) FindInBatches(result *[]*sqlentity.InterviewMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i interviewMessageDo) Attrs(attrs ...field.AssignExpr) IInterviewMessageDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i interviewMessageDo) Assign(attrs ...field.AssignExpr) IInterviewMessageDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i interviewMessageDo) Joins(fields ...field.RelationField) IInterviewMessageDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i interviewMessageDo) Preload(fields ...field.RelationField) IInterviewMessageDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i interviewMessageDo) FirstOrInit() (*sqlentity.InterviewMessage, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.InterviewMessage), nil
	}
}

func (i interviewMessageDo) FirstOrCreate() (*sqlentity.InterviewMessage, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.InterviewMessage), nil
	}
}

func (i interviewMessageDo) FindByPage(offset int, limit int) (result []*sqlentity.InterviewMessage, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i interviewMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i interviewMessageDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i interviewMessageDo) Delete(models ...*sqlentity.InterviewMessage) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *interviewMessageDo) withDO(do gen.Dao) *interviewMessageDo {
	i.DO = *do.(*gen.DO)
	return i
}
