// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlfunc

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zpi/server/shared/dal/sqlentity"
)

func newResume(db *gorm.DB, opts ...gen.DOOption) resume {
	_resume := resume{}

	_resume.resumeDo.UseDB(db, opts...)
	_resume.resumeDo.UseModel(&sqlentity.Resume{})

	tableName := _resume.resumeDo.TableName()
	_resume.ALL = field.NewAsterisk(tableName)
	_resume.ID = field.NewUint64(tableName, "id")
	_resume.UserID = field.NewUint64(tableName, "user_id")
	_resume.FileURL = field.NewString(tableName, "file_url")
	_resume.ParsedContent = field.NewString(tableName, "parsed_content")
	_resume.FileName = field.NewString(tableName, "file_name")
	_resume.FileSize = field.NewInt64(tableName, "file_size")
	_resume.FileType = field.NewString(tableName, "file_type")
	_resume.ParseStatus = field.NewInt32(tableName, "parse_status")
	_resume.CreatedAt = field.NewTime(tableName, "created_at")
	_resume.UpdatedAt = field.NewTime(tableName, "updated_at")
	_resume.DeletedAt = field.NewField(tableName, "deleted_at")

	_resume.fillFieldMap()

	return _resume
}

// resume 简历表
type resume struct {
	resumeDo

	ALL           field.Asterisk
	ID            field.Uint64 // 简历ID
	UserID        field.Uint64 // 用户ID
	FileURL       field.String // 简历文件URL
	ParsedContent field.String // 解析后的简历内容（JSON格式）
	FileName      field.String // 原始文件名
	FileSize      field.Int64  // 文件大小（字节）
	FileType      field.String // 文件类型（pdf/doc/docx等）
	ParseStatus   field.Int32  // 解析状态：0-未解析，1-解析中，2-解析成功，3-解析失败
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 删除时间（软删除）

	fieldMap map[string]field.Expr
}

func (r resume) Table(newTableName string) *resume {
	r.resumeDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resume) As(alias string) *resume {
	r.resumeDo.DO = *(r.resumeDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resume) updateTableName(table string) *resume {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint64(table, "id")
	r.UserID = field.NewUint64(table, "user_id")
	r.FileURL = field.NewString(table, "file_url")
	r.ParsedContent = field.NewString(table, "parsed_content")
	r.FileName = field.NewString(table, "file_name")
	r.FileSize = field.NewInt64(table, "file_size")
	r.FileType = field.NewString(table, "file_type")
	r.ParseStatus = field.NewInt32(table, "parse_status")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *resume) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resume) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["file_url"] = r.FileURL
	r.fieldMap["parsed_content"] = r.ParsedContent
	r.fieldMap["file_name"] = r.FileName
	r.fieldMap["file_size"] = r.FileSize
	r.fieldMap["file_type"] = r.FileType
	r.fieldMap["parse_status"] = r.ParseStatus
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r resume) clone(db *gorm.DB) resume {
	r.resumeDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resume) replaceDB(db *gorm.DB) resume {
	r.resumeDo.ReplaceDB(db)
	return r
}

type resumeDo struct{ gen.DO }

type IResumeDo interface {
	gen.SubQuery
	Debug() IResumeDo
	WithContext(ctx context.Context) IResumeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResumeDo
	WriteDB() IResumeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResumeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResumeDo
	Not(conds ...gen.Condition) IResumeDo
	Or(conds ...gen.Condition) IResumeDo
	Select(conds ...field.Expr) IResumeDo
	Where(conds ...gen.Condition) IResumeDo
	Order(conds ...field.Expr) IResumeDo
	Distinct(cols ...field.Expr) IResumeDo
	Omit(cols ...field.Expr) IResumeDo
	Join(table schema.Tabler, on ...field.Expr) IResumeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResumeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResumeDo
	Group(cols ...field.Expr) IResumeDo
	Having(conds ...gen.Condition) IResumeDo
	Limit(limit int) IResumeDo
	Offset(offset int) IResumeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeDo
	Unscoped() IResumeDo
	Create(values ...*sqlentity.Resume) error
	CreateInBatches(values []*sqlentity.Resume, batchSize int) error
	Save(values ...*sqlentity.Resume) error
	First() (*sqlentity.Resume, error)
	Take() (*sqlentity.Resume, error)
	Last() (*sqlentity.Resume, error)
	Find() ([]*sqlentity.Resume, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlentity.Resume, err error)
	FindInBatches(result *[]*sqlentity.Resume, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlentity.Resume) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResumeDo
	Assign(attrs ...field.AssignExpr) IResumeDo
	Joins(fields ...field.RelationField) IResumeDo
	Preload(fields ...field.RelationField) IResumeDo
	FirstOrInit() (*sqlentity.Resume, error)
	FirstOrCreate() (*sqlentity.Resume, error)
	FindByPage(offset int, limit int) (result []*sqlentity.Resume, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResumeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resumeDo) Debug() IResumeDo {
	return r.withDO(r.DO.Debug())
}

func (r resumeDo) WithContext(ctx context.Context) IResumeDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumeDo) ReadDB() IResumeDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumeDo) WriteDB() IResumeDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumeDo) Session(config *gorm.Session) IResumeDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumeDo) Clauses(conds ...clause.Expression) IResumeDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumeDo) Returning(value interface{}, columns ...string) IResumeDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumeDo) Not(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumeDo) Or(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumeDo) Select(conds ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumeDo) Where(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumeDo) Order(conds ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumeDo) Distinct(cols ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumeDo) Omit(cols ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumeDo) Join(table schema.Tabler, on ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResumeDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumeDo) RightJoin(table schema.Tabler, on ...field.Expr) IResumeDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumeDo) Group(cols ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumeDo) Having(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumeDo) Limit(limit int) IResumeDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumeDo) Offset(offset int) IResumeDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumeDo) Unscoped() IResumeDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumeDo) Create(values ...*sqlentity.Resume) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumeDo) CreateInBatches(values []*sqlentity.Resume, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumeDo) Save(values ...*sqlentity.Resume) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumeDo) First() (*sqlentity.Resume, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Resume), nil
	}
}

func (r resumeDo) Take() (*sqlentity.Resume, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Resume), nil
	}
}

func (r resumeDo) Last() (*sqlentity.Resume, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Resume), nil
	}
}

func (r resumeDo) Find() ([]*sqlentity.Resume, error) {
	result, err := r.DO.Find()
	return result.([]*sqlentity.Resume), err
}

func (r resumeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlentity.Resume, err error) {
	buf := make([]*sqlentity.Resume, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumeDo) FindInBatches(result *[]*sqlentity.Resume, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumeDo) Attrs(attrs ...field.AssignExpr) IResumeDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumeDo) Assign(attrs ...field.AssignExpr) IResumeDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumeDo) Joins(fields ...field.RelationField) IResumeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumeDo) Preload(fields ...field.RelationField) IResumeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumeDo) FirstOrInit() (*sqlentity.Resume, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Resume), nil
	}
}

func (r resumeDo) FirstOrCreate() (*sqlentity.Resume, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Resume), nil
	}
}

func (r resumeDo) FindByPage(offset int, limit int) (result []*sqlentity.Resume, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumeDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumeDo) Delete(models ...*sqlentity.Resume) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumeDo) withDO(do gen.Dao) *resumeDo {
	r.DO = *do.(*gen.DO)
	return r
}
