// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlfunc

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zpi/server/shared/dal/sqlentity"
)

func newStorage(db *gorm.DB, opts ...gen.DOOption) storage {
	_storage := storage{}

	_storage.storageDo.UseDB(db, opts...)
	_storage.storageDo.UseModel(&sqlentity.Storage{})

	tableName := _storage.storageDo.TableName()
	_storage.ALL = field.NewAsterisk(tableName)
	_storage.ID = field.NewUint64(tableName, "id")
	_storage.UserID = field.NewUint64(tableName, "user_id")
	_storage.FileName = field.NewString(tableName, "file_name")
	_storage.FilePath = field.NewString(tableName, "file_path")
	_storage.FileSize = field.NewInt64(tableName, "file_size")
	_storage.FileType = field.NewString(tableName, "file_type")
	_storage.FileExt = field.NewString(tableName, "file_ext")
	_storage.StorageType = field.NewString(tableName, "storage_type")
	_storage.Bucket = field.NewString(tableName, "bucket")
	_storage.ObjectKey = field.NewString(tableName, "object_key")
	_storage.URL = field.NewString(tableName, "url")
	_storage.ThumbnailURL = field.NewString(tableName, "thumbnail_url")
	_storage.Md5 = field.NewString(tableName, "md5")
	_storage.Sha256 = field.NewString(tableName, "sha256")
	_storage.Status = field.NewInt32(tableName, "status")
	_storage.UploadIP = field.NewString(tableName, "upload_ip")
	_storage.DownloadCount = field.NewInt32(tableName, "download_count")
	_storage.Metadata = field.NewString(tableName, "metadata")
	_storage.CreatedAt = field.NewTime(tableName, "created_at")
	_storage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_storage.DeletedAt = field.NewField(tableName, "deleted_at")

	_storage.fillFieldMap()

	return _storage
}

// storage 存储表
type storage struct {
	storageDo

	ALL           field.Asterisk
	ID            field.Uint64 // 存储ID
	UserID        field.Uint64 // 用户ID
	FileName      field.String // 文件名
	FilePath      field.String // 文件路径
	FileSize      field.Int64  // 文件大小（字节）
	FileType      field.String // 文件类型（MIME类型）
	FileExt       field.String // 文件扩展名
	StorageType   field.String // 存储类型：local-本地，oss-对象存储，s3-S3
	Bucket        field.String // 存储桶名称
	ObjectKey     field.String // 对象键
	URL           field.String // 访问URL
	ThumbnailURL  field.String // 缩略图URL
	Md5           field.String // MD5哈希值
	Sha256        field.String // SHA256哈希值
	Status        field.Int32  // 状态：0-已删除，1-正常
	UploadIP      field.String // 上传IP
	DownloadCount field.Int32  // 下载次数
	Metadata      field.String // 元数据（JSON）
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 删除时间（软删除）

	fieldMap map[string]field.Expr
}

func (s storage) Table(newTableName string) *storage {
	s.storageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s storage) As(alias string) *storage {
	s.storageDo.DO = *(s.storageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *storage) updateTableName(table string) *storage {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.UserID = field.NewUint64(table, "user_id")
	s.FileName = field.NewString(table, "file_name")
	s.FilePath = field.NewString(table, "file_path")
	s.FileSize = field.NewInt64(table, "file_size")
	s.FileType = field.NewString(table, "file_type")
	s.FileExt = field.NewString(table, "file_ext")
	s.StorageType = field.NewString(table, "storage_type")
	s.Bucket = field.NewString(table, "bucket")
	s.ObjectKey = field.NewString(table, "object_key")
	s.URL = field.NewString(table, "url")
	s.ThumbnailURL = field.NewString(table, "thumbnail_url")
	s.Md5 = field.NewString(table, "md5")
	s.Sha256 = field.NewString(table, "sha256")
	s.Status = field.NewInt32(table, "status")
	s.UploadIP = field.NewString(table, "upload_ip")
	s.DownloadCount = field.NewInt32(table, "download_count")
	s.Metadata = field.NewString(table, "metadata")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *storage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *storage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 21)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["file_name"] = s.FileName
	s.fieldMap["file_path"] = s.FilePath
	s.fieldMap["file_size"] = s.FileSize
	s.fieldMap["file_type"] = s.FileType
	s.fieldMap["file_ext"] = s.FileExt
	s.fieldMap["storage_type"] = s.StorageType
	s.fieldMap["bucket"] = s.Bucket
	s.fieldMap["object_key"] = s.ObjectKey
	s.fieldMap["url"] = s.URL
	s.fieldMap["thumbnail_url"] = s.ThumbnailURL
	s.fieldMap["md5"] = s.Md5
	s.fieldMap["sha256"] = s.Sha256
	s.fieldMap["status"] = s.Status
	s.fieldMap["upload_ip"] = s.UploadIP
	s.fieldMap["download_count"] = s.DownloadCount
	s.fieldMap["metadata"] = s.Metadata
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s storage) clone(db *gorm.DB) storage {
	s.storageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s storage) replaceDB(db *gorm.DB) storage {
	s.storageDo.ReplaceDB(db)
	return s
}

type storageDo struct{ gen.DO }

type IStorageDo interface {
	gen.SubQuery
	Debug() IStorageDo
	WithContext(ctx context.Context) IStorageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStorageDo
	WriteDB() IStorageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStorageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStorageDo
	Not(conds ...gen.Condition) IStorageDo
	Or(conds ...gen.Condition) IStorageDo
	Select(conds ...field.Expr) IStorageDo
	Where(conds ...gen.Condition) IStorageDo
	Order(conds ...field.Expr) IStorageDo
	Distinct(cols ...field.Expr) IStorageDo
	Omit(cols ...field.Expr) IStorageDo
	Join(table schema.Tabler, on ...field.Expr) IStorageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStorageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStorageDo
	Group(cols ...field.Expr) IStorageDo
	Having(conds ...gen.Condition) IStorageDo
	Limit(limit int) IStorageDo
	Offset(offset int) IStorageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStorageDo
	Unscoped() IStorageDo
	Create(values ...*sqlentity.Storage) error
	CreateInBatches(values []*sqlentity.Storage, batchSize int) error
	Save(values ...*sqlentity.Storage) error
	First() (*sqlentity.Storage, error)
	Take() (*sqlentity.Storage, error)
	Last() (*sqlentity.Storage, error)
	Find() ([]*sqlentity.Storage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlentity.Storage, err error)
	FindInBatches(result *[]*sqlentity.Storage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*sqlentity.Storage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStorageDo
	Assign(attrs ...field.AssignExpr) IStorageDo
	Joins(fields ...field.RelationField) IStorageDo
	Preload(fields ...field.RelationField) IStorageDo
	FirstOrInit() (*sqlentity.Storage, error)
	FirstOrCreate() (*sqlentity.Storage, error)
	FindByPage(offset int, limit int) (result []*sqlentity.Storage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStorageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s storageDo) Debug() IStorageDo {
	return s.withDO(s.DO.Debug())
}

func (s storageDo) WithContext(ctx context.Context) IStorageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s storageDo) ReadDB() IStorageDo {
	return s.Clauses(dbresolver.Read)
}

func (s storageDo) WriteDB() IStorageDo {
	return s.Clauses(dbresolver.Write)
}

func (s storageDo) Session(config *gorm.Session) IStorageDo {
	return s.withDO(s.DO.Session(config))
}

func (s storageDo) Clauses(conds ...clause.Expression) IStorageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s storageDo) Returning(value interface{}, columns ...string) IStorageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s storageDo) Not(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s storageDo) Or(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s storageDo) Select(conds ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s storageDo) Where(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s storageDo) Order(conds ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s storageDo) Distinct(cols ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s storageDo) Omit(cols ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s storageDo) Join(table schema.Tabler, on ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s storageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStorageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s storageDo) RightJoin(table schema.Tabler, on ...field.Expr) IStorageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s storageDo) Group(cols ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s storageDo) Having(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s storageDo) Limit(limit int) IStorageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s storageDo) Offset(offset int) IStorageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s storageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStorageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s storageDo) Unscoped() IStorageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s storageDo) Create(values ...*sqlentity.Storage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s storageDo) CreateInBatches(values []*sqlentity.Storage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s storageDo) Save(values ...*sqlentity.Storage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s storageDo) First() (*sqlentity.Storage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Storage), nil
	}
}

func (s storageDo) Take() (*sqlentity.Storage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Storage), nil
	}
}

func (s storageDo) Last() (*sqlentity.Storage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Storage), nil
	}
}

func (s storageDo) Find() ([]*sqlentity.Storage, error) {
	result, err := s.DO.Find()
	return result.([]*sqlentity.Storage), err
}

func (s storageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sqlentity.Storage, err error) {
	buf := make([]*sqlentity.Storage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s storageDo) FindInBatches(result *[]*sqlentity.Storage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s storageDo) Attrs(attrs ...field.AssignExpr) IStorageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s storageDo) Assign(attrs ...field.AssignExpr) IStorageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s storageDo) Joins(fields ...field.RelationField) IStorageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s storageDo) Preload(fields ...field.RelationField) IStorageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s storageDo) FirstOrInit() (*sqlentity.Storage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Storage), nil
	}
}

func (s storageDo) FirstOrCreate() (*sqlentity.Storage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sqlentity.Storage), nil
	}
}

func (s storageDo) FindByPage(offset int, limit int) (result []*sqlentity.Storage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s storageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s storageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s storageDo) Delete(models ...*sqlentity.Storage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *storageDo) withDO(do gen.Dao) *storageDo {
	s.DO = *do.(*gen.DO)
	return s
}
