// Code generated by hertz generator.

package question

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _questionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoritequestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unfavoritequestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfavoritequestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getquestionlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getquestiondetailMw() []app.HandlerFunc {
	// your code...
	return nil
}
